/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2024-03-07 13:38:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.text.SimpleDateFormat;
import java.util.Date;
import com.DB.DBConnection;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.sql.*;
import java.time.temporal.ChronoUnit;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1542635938000L));
    _jspx_dependants.put("jar:file:/E:/WORKSPACE/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HSL031220/WEB-INF/lib/standard.jar!/META-INF/c-1_0-rt.tld", Long.valueOf(1098691290000L));
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.2.1.jar", Long.valueOf(1542635950000L));
    _jspx_dependants.put("jar:file:/E:/WORKSPACE/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HSL031220/WEB-INF/lib/struts2-core-2.2.1.jar!/META-INF/struts-tags.tld", Long.valueOf(1279356888000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.time.temporal.ChronoUnit");
    _jspx_imports_classes.add("com.DB.DBConnection");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("java.time.LocalDate");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("java.text.DateFormat");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\t<title>High Seas Logistics Pvt. Ltd.</title>\r\n");
      out.write(" \t<link href=\"configure/css/online.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"configure/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"configure/css/nifty.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"configure/plugins/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"configure/plugins/animate-css/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"configure/plugins/morris-js/morris.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"configure/plugins/switchery/switchery.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"configure/plugins/bootstrap-select/bootstrap-select.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"configure/css/demo/nifty-demo.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"configure/plugins/pace/pace.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<script src=\"configure/plugins/pace/pace.min.js\"></script>\r\n");
      out.write("\t<script>  \r\n");
      out.write("\twindow.onload=function(){getTime();}  \r\n");
      out.write("\tfunction getTime(){  \r\n");
      out.write("\tvar today=new Date();  \r\n");
      out.write("\tvar h=today.getHours();  \r\n");
      out.write("\tvar m=today.getMinutes();  \r\n");
      out.write("\tvar s=today.getSeconds();  \r\n");
      out.write("\t// add a zero in front of numbers<10  \r\n");
      out.write("\tm=checkTime(m);  \r\n");
      out.write("\ts=checkTime(s);  \r\n");
      out.write("\tdocument.getElementById('txt').innerHTML=h+\":\"+m+\":\"+s;  \r\n");
      out.write("\tsetTimeout(function(){getTime()},1000);  \r\n");
      out.write("\t}  \r\n");
      out.write("\t//setInterval(\"getTime()\",1000);//another way  \r\n");
      out.write("\tfunction checkTime(i){  \r\n");
      out.write("\tif (i<10){  \r\n");
      out.write("\t  i=\"0\" + i;  \r\n");
      out.write("\t }  \r\n");
      out.write("\treturn i;  \r\n");
      out.write("\t}  \r\n");
      out.write("</script> \r\n");
      out.write("    \r\n");
      out.write("<script>  \r\n");
      out.write("   \r\n");
      out.write("    var date=new Date();  \r\n");
      out.write("    var day=date.getDate();  \r\n");
      out.write("    var month=date.getMonth()+1;  \r\n");
      out.write("    var year=date.getFullYear(); \r\n");
      out.write("    document.getElementById(\"date\").innerHTML=Date is: day+\"/\"+month+\"/\"+year;\r\n");
      out.write("   \r\n");
      out.write(" </script> \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("  <script>\r\n");
      out.write(" \r\n");
      out.write(" function TodaysVaccinations() {\r\n");
      out.write(" \t\r\n");
      out.write("     ");

     
     String response1="0";
   
     int days=0;
     
     int count=0;
    
     try
     {
    	 
    	 DBConnection connection=new DBConnection();
    	 Connection conn=connection.getConnection();
     	
     	
     	
     	PreparedStatement preparedStatement112 = conn
 		.prepareStatement("select *  from alert_table WHERE   status='0' ");
 		
     	//System.out.print("SQL:"+preparedStatement112);
 		
 			ResultSet resultSet12 = preparedStatement112.executeQuery();

 		while (resultSet12.next()) {
 	
 	
 			DateFormat df = new SimpleDateFormat("yyyy-MM-dd"); 
			
			Date datee = new Date();
					
			String dateBeforeString = df.format(datee);
			String dateAfterString = resultSet12.getString("exp_date");
				
			//Parsing the date
			LocalDate dateBefore = LocalDate.parse(dateBeforeString);
			LocalDate dateAfter = LocalDate.parse(dateAfterString);
				
			//calculating number of days in between
			long noOfDaysBetween = ChronoUnit.DAYS.between(dateBefore, dateAfter);
				
			//displaying the number of days
			System.out.println(noOfDaysBetween);
 			
			
			PreparedStatement pst1 = conn.prepareStatement("select no_of_days from no_of_days ");
			ResultSet rs1 = pst1.executeQuery();
		
			if(rs1.next())
			{
					days=rs1.getInt("no_of_days");
			}
			
			
			if(noOfDaysBetween <=days)
			{
				count++;
			}
			
 					
 		
 			}
 		
 		
 		response1 = String.valueOf(count) ;
 		
     }
     catch(Exception e)
     {
     e.printStackTrace();
     }
     
     finally{
    	 
    	 
    	 DBConnection.closeConnection();
     }
     
      
     
      out.write("\r\n");
      out.write("     } \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \t\r\n");
      out.write(" function TodaysVaccinations2() {\r\n");
      out.write("\t \t\r\n");
      out.write("     ");

     
     String response2="0";
   
      
     try
     {
    	 
    	 DBConnection connection=new DBConnection();
    	 Connection conn=connection.getConnection();
     	
     	
     	
     	PreparedStatement preparedStatement112 = conn
 		.prepareStatement("select count(*) as count2  from inquiry WHERE  status='0'  ");
 		
     	//System.out.print("SQL:"+preparedStatement112);
 		
 			ResultSet resultSet12 = preparedStatement112.executeQuery();

 		while (resultSet12.next()) {
 	
 	
 			response2 = resultSet12.getString("count2") ;
 		
 			}
 		
 		
 		
 		
     }
     catch(Exception e)
     {
     e.printStackTrace();
     }
     
     finally{
    	 
    	 
    	 DBConnection.closeConnection();
     }
     
      
     
      out.write("\r\n");
      out.write("     } \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" function TodaysVaccinations3() {\r\n");
      out.write("\t \t\r\n");
      out.write("     ");

     
     String response3="0";
   
      
     try
     {
    	 
    	 DBConnection connection=new DBConnection();
    	 Connection conn=connection.getConnection();
     	
     	
     	
     	PreparedStatement preparedStatement112 = conn
 		.prepareStatement("select count(*) as count3  from pricing WHERE  status='0'  ");
 		
     	//System.out.print("SQL:"+preparedStatement112);
 		
 			ResultSet resultSet12 = preparedStatement112.executeQuery();

 		while (resultSet12.next()) {
 	
 	
 			response3 = resultSet12.getString("count3") ;
 		
 			}
 		
 		
 		
 		
     }
     catch(Exception e)
     {
     e.printStackTrace();
     }
     
     finally{
    	 
    	 
    	 DBConnection.closeConnection();
     }
     
      
     
      out.write("\r\n");
      out.write("     } \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" function TodaysVaccinations4() {\r\n");
      out.write("\t \t\r\n");
      out.write("     ");

     
     String response4="0";
   
      
     try
     {
    	 
    	 DBConnection connection=new DBConnection();
    	 Connection conn=connection.getConnection();
     	
     	
     	
     	PreparedStatement preparedStatement112 = conn
 		.prepareStatement("select count(*) as count4  from quotation WHERE  status='0'  ");
 		
     	//System.out.print("SQL:"+preparedStatement112);
 		
 			ResultSet resultSet12 = preparedStatement112.executeQuery();

 		while (resultSet12.next()) {
 	
 	
 			response4 = resultSet12.getString("count4") ;
 		
 			}
 		
 		
 		
 		
     }
     catch(Exception e)
     {
     e.printStackTrace();
     }
     
     finally{
    	 
    	 
    	 DBConnection.closeConnection();
     }
     
      
     
      out.write("\r\n");
      out.write("     } \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" function TodaysVaccinations5() {\r\n");
      out.write("\t \t\r\n");
      out.write("     ");

     
     String response5="0";
   
      
     try
     {
    	 
    	 DBConnection connection=new DBConnection();
    	 Connection conn=connection.getConnection();
     	
     	
     	
     	PreparedStatement preparedStatement112 = conn
 		.prepareStatement("select count(*) as count5  from pricing WHERE  status='2'  ");
 		
     	//System.out.print("SQL:"+preparedStatement112);
 		
 			ResultSet resultSet12 = preparedStatement112.executeQuery();

 		while (resultSet12.next()) {
 	
 	
 			response5 = resultSet12.getString("count5") ;
 		
 			}
 		
 		
 		
 		
     }
     catch(Exception e)
     {
     e.printStackTrace();
     }
     
     finally{
    	 
    	 
    	 DBConnection.closeConnection();
     }
     
      
     
      out.write("\r\n");
      out.write("     } \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" function TodaysVaccinations6() {\r\n");
      out.write("\t \t\r\n");
      out.write("     ");

     
     String response6="0";
   
      
     try
     {
    	 
    	 DBConnection connection=new DBConnection();
    	 Connection conn=connection.getConnection();
     	
     	
     	
     	PreparedStatement preparedStatement112 = conn
 		.prepareStatement("select count(*) as count6  from order_table WHERE  status='0'  ");
 		
     	//System.out.print("SQL:"+preparedStatement112);
 		
 			ResultSet resultSet12 = preparedStatement112.executeQuery();

 		while (resultSet12.next()) {
 	
 	
 			response6 = resultSet12.getString("count6") ;
 		
 			}
 		
 		
 		
 		
     }
     catch(Exception e)
     {
     e.printStackTrace();
     }
     
     finally{
    	 
    	 
    	 DBConnection.closeConnection();
     }
     
      
     
      out.write("\r\n");
      out.write("     } \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" function TodaysVaccinations7() {\r\n");
      out.write("\t \t\r\n");
      out.write("     ");

     
     String response7="0";
   
      
     try
     {
    	 
    	 DBConnection connection=new DBConnection();
    	 Connection conn=connection.getConnection();
     	
     	
     	
     	PreparedStatement preparedStatement112 = conn
 		.prepareStatement("select count(*) as count7  from lr WHERE  status='0'  ");
 		
     	//System.out.print("SQL:"+preparedStatement112);
 		
 			ResultSet resultSet12 = preparedStatement112.executeQuery();

 		while (resultSet12.next()) {
 	
 	
 			response7 = resultSet12.getString("count7") ;
 		
 			}
 		
 		
 		
 		
     }
     catch(Exception e)
     {
     e.printStackTrace();
     }
     
     finally{
    	 
    	 
    	 DBConnection.closeConnection();
     }
     
      
     
      out.write("\r\n");
      out.write("     } \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" function TodaysVaccinations8() {\r\n");
      out.write("\t \t\r\n");
      out.write("     ");

     
     String response8="0";
   
      
     try
     {
    	 
    	 DBConnection connection=new DBConnection();
    	 Connection conn=connection.getConnection();
     	
     	
     	
     	PreparedStatement preparedStatement112 = conn
 		.prepareStatement("select count(*) as count8  from delivery_done1 WHERE  status='0'  ");
 		
     	//System.out.print("SQL:"+preparedStatement112);
 		
 			ResultSet resultSet12 = preparedStatement112.executeQuery();

 		while (resultSet12.next()) {
 	
 	
 			response8 = resultSet12.getString("count8") ;
 		
 			}
 		
 		
 		
 		
     }
     catch(Exception e)
     {
     e.printStackTrace();
     }
     
     finally{
    	 
    	 
    	 DBConnection.closeConnection();
     }
     
      
     
      out.write("\r\n");
      out.write("     } \r\n");
      out.write(" \r\n");
      out.write(" </script>   \r\n");
      out.write(" \r\n");
      out.write(" <script>\r\n");
      out.write("\tfunction logout() {\r\n");
      out.write("\r\n");
      out.write("\tvar currentURL = \"Logout\";\r\n");
      out.write("\t\r\n");
      out.write("\t\tvar okdelete = confirm(\"Are You Sure Want to Logout!\");\r\n");
      out.write("\r\n");
      out.write("\t\tif (okdelete)\r\n");
      out.write("\r\n");
      out.write("\t\t{\r\n");
      out.write("\r\n");
      out.write("\t\t\tlocation.href = currentURL;\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\t\r\n");
      out.write("$(function() {\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tif(document.getElementById(\"mys\").value == \"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tlocation.href=\"SessionOut\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\t\r\n");
      out.write(" \r\n");
      out.write(" <style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".badge {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: -1px;\r\n");
      out.write("  right: -4px;\r\n");
      out.write("  padding: 3px 7px;\r\n");
      out.write("  border-radius: 50%;\r\n");
      out.write("  background-color: #fc466d;\r\n");
      out.write("  color: white;\r\n");
      out.write("}\r\n");
      out.write("</style> \r\n");
      out.write(" \r\n");
      out.write(" <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">   \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t\t<header id=\"navbar\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"navbar-container\" class=\"boxed\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t\t<a href=\"dashboard\" class=\"navbar-brand\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"brand-title\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"brand-text\"><img style=\"margin-left: -10px;    width: 117px;    height: 46px;\" alt=\"\" src=\"configure/img/logo.png\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"navbar-content clearfix\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-top-links pull-left\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!--Navigation toogle button-->\r\n");
      out.write("\t\t\t\t\t\t<li class=\"tgl-menu-btn\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"mainnav-toggle\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fa fa-navicon fa-lg\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</ul>\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- <ul class=\"nav navbar-top-links pull-right\">\r\n");
      out.write("      \r\n");
      out.write("     \t\t\t \t\t<li><a  class=\"btn btn-primary\"> </a></li>\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t\t\t</ul> -->\r\n");
      out.write("    \t\t\t\t\r\n");
      out.write("    \t\t\t\t\r\n");
      out.write("    \t\t\t\t\r\n");
      out.write("    \t\t\t\t<ul class=\"nav navbar-top-links pull-right\">\r\n");
      out.write("      \r\n");
      out.write("     \t\t\t \t\t<li><a onclick=\"logout();\" class=\"btn btn-primary\"> Logout</a></li>\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");
      out.write("\r\n");
      out.write("    \t\t\t\t\r\n");
      out.write("    \t\t\t\t\r\n");
      out.write("    \t\t\t\t<ul class=\"nav navbar-top-links pull-right\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"Pricing Pending\">\r\n");
      out.write("    \t\t\t\t\t\r\n");
      out.write("    \t\t\t\t\t<li>\r\n");
      out.write("    \t\t\t\t\t\t<a href=\"EnquiryReport\" class=\"notification\">\r\n");
      out.write(" \t\t\t\t\t\t\t \r\n");
      out.write(" \t\t\t\t\t\t\t \t<i class=\"fa fa-money\" style=\"color:#229954    ;font-size:25px\" ></i>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\r\n");
      out.write("  \t\t\t\t\t\t\t\t<span class=\"badge\">");
      out.print(response2 );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-top-links pull-right\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"Quotation Pending\">\r\n");
      out.write("    \t\t\t\t\t\r\n");
      out.write("    \t\t\t\t\t<li>\r\n");
      out.write("    \t\t\t\t\t\t<a href=\"PricingReport\" class=\"notification\">\t\r\n");
      out.write(" \t\t\t\t\t\t\t \r\n");
      out.write(" \t\t\t\t\t\t\t \t<i class=\"fa fa-pencil-square-o\" style=\"color:#ff3300    ;font-size:25px\" ></i>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\r\n");
      out.write("  \t\t\t\t\t\t\t\t<span class=\"badge\">");
      out.print(response3 );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-top-links pull-right\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"Quotation Finalize Pending\">\r\n");
      out.write("    \t\t\t\t\t\r\n");
      out.write("    \t\t\t\t\t<li>\r\n");
      out.write("    \t\t\t\t\t\t<a href=\"QuotationReport\" class=\"notification\">\r\n");
      out.write(" \t\t\t\t\t\t\t \r\n");
      out.write(" \t\t\t\t\t\t\t \t<i class=\"fa fa-quote-left\" style=\"color:#ccff66    ;font-size:25px\" ></i>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\r\n");
      out.write("  \t\t\t\t\t\t\t\t<span class=\"badge\">");
      out.print(response4 );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-top-links pull-right\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"Vehicle Assign Pending\">\r\n");
      out.write("    \t\t\t\t\t\r\n");
      out.write("    \t\t\t\t\t<li>\r\n");
      out.write("    \t\t\t\t\t\t<a href=\"PricingReport1\" class=\"notification\">\r\n");
      out.write(" \t\t\t\t\t\t\t \r\n");
      out.write(" \t\t\t\t\t\t\t \t<i class=\"fa fa-truck\" style=\"color:#660066    ;font-size:25px\" ></i>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\r\n");
      out.write("  \t\t\t\t\t\t\t\t<span class=\"badge\">");
      out.print(response5 );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-top-links pull-right\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"LR Pending\">\r\n");
      out.write("    \t\t\t\t\t\r\n");
      out.write("    \t\t\t\t\t<li>\r\n");
      out.write("    \t\t\t\t\t\t<a href=\"OrderReport\" class=\"notification\">\r\n");
      out.write(" \t\t\t\t\t\t\t \r\n");
      out.write(" \t\t\t\t\t\t\t \t<i class=\"fa fa-bell\" style=\"color:#990099    ;font-size:25px\" ></i>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\r\n");
      out.write("  \t\t\t\t\t\t\t\t<span class=\"badge\">");
      out.print(response6 );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-top-links pull-right\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"Delivery Pending\">\r\n");
      out.write("    \t\t\t\t\t\r\n");
      out.write("    \t\t\t\t\t<li>\r\n");
      out.write("    \t\t\t\t\t\t<a href=\"lr_Reports\" class=\"notification\">\r\n");
      out.write(" \t\t\t\t\t\t\t \r\n");
      out.write(" \t\t\t\t\t\t\t \t<i class=\"fa fa-hdd-o\" style=\"color:#660066    ;font-size:25px\" ></i>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\r\n");
      out.write("  \t\t\t\t\t\t\t\t<span class=\"badge\">");
      out.print(response7 );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-top-links pull-right\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"Invoice Pending\">\r\n");
      out.write("    \t\t\t\t\t\r\n");
      out.write("    \t\t\t\t\t<li>\r\n");
      out.write("    \t\t\t\t\t\t<a href=\"delivery_done_Reports1\" class=\"notification\">\r\n");
      out.write(" \t\t\t\t\t\t\t \r\n");
      out.write(" \t\t\t\t\t\t\t \t<i class=\"fa fa-inr\" style=\"color:#00cc00    ;font-size:25px\" ></i>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\r\n");
      out.write("  \t\t\t\t\t\t\t\t<span class=\"badge\">");
      out.print(response8 );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-top-links pull-right\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"Expected Alert\">\r\n");
      out.write("    \t\t\t\t\t\r\n");
      out.write("    \t\t\t\t\t<li>\r\n");
      out.write("    \t\t\t\t\t\t<a href=\"AlertExpectedReport\" class=\"notification\">\r\n");
      out.write(" \t\t\t\t\t\t\t \r\n");
      out.write(" \t\t\t\t\t\t\t \t<i class=\"fa fa-exclamation-triangle\" style=\"color:#3333ff    ;font-size:25px\" ></i>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\r\n");
      out.write("  \t\t\t\t\t\t\t\t<span class=\"badge\">");
      out.print(response1 );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-top-links pull-right\">\r\n");
      out.write("      \r\n");
      out.write("     \t\t\t \t\t<li><input type=\"hidden\" value='");
      if (_jspx_meth_s_005fproperty_005f0(_jspx_page_context))
        return;
      out.write("' id=\"mys\" /></li>\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t\t\t</ul>\r\n");
      out.write("    \t\t\t\t\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_s_005fproperty_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f0 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f0.setParent(null);
    // /common/header.jsp(739,43) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f0.setValue("#session.USER_PROFILE.username");
    int _jspx_eval_s_005fproperty_005f0 = _jspx_th_s_005fproperty_005f0.doStartTag();
    if (_jspx_th_s_005fproperty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f0);
    return false;
  }
}
