/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2024-03-08 06:40:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages.form;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.Connection;
import com.DB.DBConnection;

public final class CommonInvoice_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.2.1.jar", Long.valueOf(1542635950000L));
    _jspx_dependants.put("jar:file:/E:/WORKSPACE/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HSL031220/WEB-INF/lib/struts2-core-2.2.1.jar!/META-INF/struts-tags.tld", Long.valueOf(1279356888000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("com.DB.DBConnection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fpush_0026_005fvalue;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fiterator_0026_005fvalue_005fstatus;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005felse;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fs_005fpush_0026_005fvalue = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fiterator_0026_005fvalue_005fstatus = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005felse = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fs_005fpush_0026_005fvalue.release();
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005fiterator_0026_005fvalue_005fstatus.release();
    _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fs_005felse.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<link href=\"configure/plugins/bootstrap-datepicker/bootstrap-datepicker.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"Css/jquery-1.10.2.js\" type=\"text/javascript\"></script>\r\n");
      out.write(" <!-- AutoSearch -->\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"Css/styleAS.css\" />\r\n");
      out.write("  <script src=\"js/jquery-migrate-1.2.1.js\" type=\"text/javascript\"></script>\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" media=\"all\" href=\"Css/AutoSearch/styleAS.css\" />\r\n");
      out.write("  <script src=\"jQuery_4_design/AutoSearch/AutoSearchJquerySale.js\" type=\"text/javascript\"></script>\r\n");
      out.write("  <script src=\"js/jquery.validationEngine.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("  <!-- AutoSearch -->\r\n");
      out.write("  \r\n");
      out.write("  <script src=\"js/datevalidation.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("\t<script>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tvar today = new Date(); \r\n");
      out.write("\t\tvar dd = today.getDate(); \r\n");
      out.write("\t\tvar mm = today.getMonth()+1;//January is 0! \r\n");
      out.write("\t\tvar yyyy = today.getFullYear(); \r\n");
      out.write("\t\tif(dd<10){dd='0'+dd} \r\n");
      out.write("\t\tif(mm<10){mm='0'+mm} \r\n");
      out.write("\t\t$(\"#date\").val(dd+'/'+mm+'/'+yyyy);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t <script>\r\n");
      out.write("\t\r\n");
      out.write(" function totalQty(v) {\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\tvar amount=0;\r\n");
      out.write("\r\n");
      out.write("\t\t\t$('.item-row').each(function(i, row) {\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\tvar $price = $(row).find('#ii');\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar r1 = $($price).val();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tamount=Math.abs(amount)+ Math.abs(r1);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar s=Number(document.getElementById(\"lr_amount\").value);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tdocument.getElementById(\"total\").value=amount;\r\n");
      out.write("\t\t\tdocument.getElementById(\"total12\").value=amount+s;\r\n");
      out.write("\t\t\t\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" function getAmount(v)\r\n");
      out.write(" {\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tvar amount=0;\r\n");
      out.write("\t\r\n");
      out.write("\t var $traverse_row = $(v).parents('.item-row');\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\tvar $hoardinglocation1 = $($traverse_row).find('#gg');\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\tvar tax1=$($hoardinglocation1).val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar $hoardinglocation2 = $($traverse_row).find('#hh');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar tax2=$($hoardinglocation2).val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$hoardinglocation5 = $($traverse_row).find('#ii');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('.item-row').each(function(i, row) {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tamount = tax1 * tax2;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//$hoardinglocation5 = $($traverse_row).find('#ee');\r\n");
      out.write("\t\t\t$($hoardinglocation5).val(amount.toFixed(2));\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write("\t\t\r\n");
      out.write("</script>  \r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function myFunction() {\r\n");
      out.write("  document.getElementById(\"myBtn\").disabled = true;\r\n");
      out.write(" /*  alert(\"Hiiiii\"); */\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body >\r\n");
      out.write("\t<div id=\"container\" class=\"effect mainnav-lg\">\r\n");
      out.write("\t\t<!--NAVBAR-->\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t<!--END NAVBAR-->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"boxed\">\r\n");
      out.write("\t\t\t<!--CONTENT CONTAINER-->\r\n");
      out.write("\t\t\t<div id=\"content-container\">\r\n");
      out.write("\t\t\t\t<!--Page Title-->\r\n");
      out.write("\t\t\t\t<div id=\"page-title\">\r\n");
      out.write("\t\t\t\t\t<h1 class=\"page-header text-overflow\">Invoice </h1>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--End page title-->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!--Breadcrumb-->\r\n");
      out.write("\t\t\t\t<ol class=\"breadcrumb\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Invoice</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"active\">Invoice</li>\r\n");
      out.write("\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t<!--End breadcrumb-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!--Page content-->\r\n");
      out.write("\t\t\t\t<div id=\"page-content\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"panel\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3 class=\"panel-title\"></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      if (_jspx_meth_s_005fpush_005f0(_jspx_page_context))
        return;
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--End page content-->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--END CONTENT CONTAINER-->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!--MAIN NAVIGATION-->\r\n");
      out.write("\t\t\t<nav id=\"mainnav-container\">\r\n");
      out.write("\t\t\t\t<div id=\"mainnav\">\r\n");
      out.write("\t\t\t\t\t<!--Shortcut buttons-->\r\n");
      out.write("\t\t\t\t\t<div id=\"mainnav-shortcut\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"list-unstyled\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"col-xs-4\" data-content=\"Additional Sidebar\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a id=\"demo-toggle-aside\" class=\"shortcut-grid\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-magic\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"col-xs-4\" data-content=\"Notification\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a id=\"demo-alert\" class=\"shortcut-grid\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-bullhorn\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"col-xs-4\" data-content=\"Page Alerts\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a id=\"demo-page-alert\" class=\"shortcut-grid\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-bell\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!--End shortcut buttons-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!--Menu-->\r\n");
      out.write("\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/common/leftsidebar.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t\t\t<!--End menu-->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t\t<!--END MAIN NAVIGATION-->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- FOOTER -->\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t<!-- END FOOTER -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- END OF CONTAINER -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- SETTINGS - DEMO PURPOSE ONLY -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/common/settingsForGrid.jsp", out, false);
      out.write("\r\n");
      out.write("\t<!-- END SETTINGS -->\r\n");
      out.write("\t<script src=\"configure/plugins/bootstrap-datepicker/bootstrap-datepicker.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(document)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t.ready(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t//alert('Inside fun()');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t$(\"#addRow\").bind('click',addRows);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar index = 13;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tfunction addRows(e) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttry {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar $itemsTable = $('#itemsTable1');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar $rowTemp = [\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'<tr class=\"item-row1\">',\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'<td><a id=\"deleteRow\"><img src=\"Images_4_design/AddRowDataTable/icon-minus.png\" alt=\"Remove Item\" title=\"Remove Item\"></a></td>',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'<td><input class=\"form-control\" style=\"width:120px;\"  type=\"text\" name=\"lrno11\" \tid=\"lrno\" value=\"");
      if (_jspx_meth_s_005fproperty_005f19(_jspx_page_context))
        return;
      out.write("\" readonly/></td>',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'<td><input class=\"form-control\" style=\"width:120px;\"  type=\"text\" name=\"drivername11\" id=\"drivername11\" value=\"");
      if (_jspx_meth_s_005fproperty_005f20(_jspx_page_context))
        return;
      out.write("\" /></td>',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'<td><input class=\"form-control\" style=\"width:120px;\"  type=\"text\" name=\"expdate11\"  id=\"expdate11\" value=\"");
      if (_jspx_meth_s_005fproperty_005f21(_jspx_page_context))
        return;
      out.write("\" /></td>',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'<td><input class=\"form-control\" style=\"width:120px;\"  type=\"text\" name=\"exppart11\"  id=\"exppart11\" value=\"");
      if (_jspx_meth_s_005fproperty_005f22(_jspx_page_context))
        return;
      out.write("\" /></td>',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'<td><input class=\"form-control\" style=\"width:120px;\"  type=\"text\" name=\"expamt11\"  id=\"expamt11\" value=\"");
      if (_jspx_meth_s_005fproperty_005f23(_jspx_page_context))
        return;
      out.write("\" /></td>',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'<td><input class=\"form-control\" style=\"width:120px;\"  type=\"text\" name=\"drivername11\" id=\"drivername11\" value=\"");
      if (_jspx_meth_s_005fproperty_005f24(_jspx_page_context))
        return;
      out.write("\" /></td>',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'<td><input class=\"form-control\" style=\"width:120px;\"  type=\"text\" name=\"expdate11\"  id=\"expdate11\" value=\"");
      if (_jspx_meth_s_005fproperty_005f25(_jspx_page_context))
        return;
      out.write("\" /></td>',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'<td><input class=\"form-control\" style=\"width:120px;\"  type=\"text\" name=\"exppart11\"  id=\"exppart11\" value=\"");
      if (_jspx_meth_s_005fproperty_005f26(_jspx_page_context))
        return;
      out.write("\" /></td>',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'</tr>' ]\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.join('');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar $row = $($rowTemp);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$.currentRow = $row;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$last = $('#itemsTable1')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.find(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'tbody tr:last');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$.first = $last\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.find('input:first');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$('.item-row1:last',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$itemsTable)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.after($row);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t} catch (err) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\talert(err);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t}); // End DOM\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t//Remove row when clicked\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t$(\"#deleteRow\").live('click', function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t//alert(\">>>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t$(this).parents('.item-row1').remove();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t// Hide delete Icon if we only have one row in the list.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tif ($(\".item-row1\").length < 2)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$(\"#deleteRow\").hide();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t//totalnetamt();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</script>\t\t\t\t\t\t\t \r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_s_005fpush_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:push
    org.apache.struts2.views.jsp.PushTag _jspx_th_s_005fpush_005f0 = (org.apache.struts2.views.jsp.PushTag) _005fjspx_005ftagPool_005fs_005fpush_0026_005fvalue.get(org.apache.struts2.views.jsp.PushTag.class);
    _jspx_th_s_005fpush_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fpush_005f0.setParent(null);
    // /pages/form/CommonInvoice.jsp(145,8) name = value type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fpush_005f0.setValue("im");
    int _jspx_eval_s_005fpush_005f0 = _jspx_th_s_005fpush_005f0.doStartTag();
    if (_jspx_eval_s_005fpush_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_s_005fpush_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_s_005fpush_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_s_005fpush_005f0.doInitBody();
      }
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t<form action=\"InvoiceSubmit\" class=\"form-control\"  method=\"POST\"  onsubmit=\"myFunction();\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<div class=\"panel-body\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
        out.write("\t\t\t\t\t\t\t          \r\n");
        out.write("\t\t\t\t\t\t\t          <div class=\"col-md-6\">\r\n");
        out.write("\t\t\t\t\t\t\t          <div class=\"form-group\">\r\n");
        out.write("\t\t\t\t\t\t\t                <label>Customer Name</label>\r\n");
        out.write("\t\t\t\t\t\t\t                <input type=\"text\" class=\"form-control\" value=\"");
        if (_jspx_meth_s_005fproperty_005f0(_jspx_th_s_005fpush_005f0, _jspx_page_context))
          return true;
        out.write("\" id=\"name\" name=\"name\" required >\r\n");
        out.write("\t\t\t\t\t\t\t              \r\n");
        out.write("\t\t\t\t\t\t\t               <input type=\"hidden\" class=\"form-control\" value=\"");
        if (_jspx_meth_s_005fproperty_005f1(_jspx_th_s_005fpush_005f0, _jspx_page_context))
          return true;
        out.write("\" id=\"customer_no\" name=\"customer_no\"  >\r\n");
        out.write("\t\t\t\t\t\t\t              <input type=\"hidden\" class=\"form-control\" value=\"");
        if (_jspx_meth_s_005fproperty_005f2(_jspx_th_s_005fpush_005f0, _jspx_page_context))
          return true;
        out.write("\" id=\"inquiry_id\" name=\"inquiry_id\"  >\r\n");
        out.write("\t\t\t\t\t\t\t              \r\n");
        out.write("\t\t\t\t\t\t\t              </div>\r\n");
        out.write("\t\t\t\t\t\t\t            \r\n");
        out.write("\t\t\t\t\t\t\t          </div>\r\n");
        out.write("\t\t\t\t\t\t\t          \r\n");
        out.write("\t\t\t\t\t\t\t          \r\n");
        out.write("\t\t\t\t\t\t\t          <div class=\"col-md-6\">\r\n");
        out.write("\t\t\t\t\t\t\t          <div class=\"form-group\">\r\n");
        out.write("\t\t\t\t\t\t\t                <label>Invoice No </label>\r\n");
        out.write("\t\t\t\t\t\t\t                <input type=\"text\" class=\"form-control\" value=\"");
        if (_jspx_meth_s_005fproperty_005f3(_jspx_th_s_005fpush_005f0, _jspx_page_context))
          return true;
        out.write("\" name=\"invoiceno\" id=\"invoiceno\"  readonly  required>\r\n");
        out.write("\t\t\t\t\t\t\t              </div>\r\n");
        out.write("\t\t\t\t\t\t\t            \r\n");
        out.write("\t\t\t\t\t\t\t          </div>\r\n");
        out.write("\t\t\t\t\t\t\t          \r\n");
        out.write("\t\t\t\t\t\t\t              \r\n");
        out.write("\t\t\t\t\t\t\t          </div>\r\n");
        out.write("\t\t\t\t\t\t\t          \r\n");
        out.write("\t\t\t\t\t\t\t          \r\n");
        out.write("\t\t\t\t\t\t\t          \r\n");
        out.write("\t\t\t\t\t\t\t          <div class=\"row\">\r\n");
        out.write("\t\t\t\t\t\t\t          \r\n");
        out.write("\t\t\t\t\t\t\t          <div class=\"col-md-6\">\r\n");
        out.write("\t\t\t\t\t\t\t          <div class=\"form-group\">\r\n");
        out.write("\t\t\t\t\t\t\t                <label>Address</label>\r\n");
        out.write("\t\t\t\t\t\t\t                <input type=\"text\" class=\"form-control\" value=\"");
        if (_jspx_meth_s_005fproperty_005f4(_jspx_th_s_005fpush_005f0, _jspx_page_context))
          return true;
        out.write("\" id=\"address\" name=\"address\" required >\r\n");
        out.write("\t\t\t\t\t\t\t              </div>\r\n");
        out.write("\t\t\t\t\t\t\t            \r\n");
        out.write("\t\t\t\t\t\t\t          </div>\r\n");
        out.write("\t\t\t\t\t\t\t          \r\n");
        out.write("\t\t\t\t\t\t\t          \r\n");
        out.write("\t\t\t\t\t\t\t          <div class=\"col-md-6\">\r\n");
        out.write("\t\t\t\t\t\t\t          <div class=\"form-group\">\r\n");
        out.write("\t\t\t\t\t\t\t                <label>Date</label>\r\n");
        out.write("\t\t\t\t\t\t\t                <input type=\"text\" class=\"form-control\"  name=\"date\" id=\"date\" value=\"");
        if (_jspx_meth_s_005fproperty_005f5(_jspx_th_s_005fpush_005f0, _jspx_page_context))
          return true;
        out.write("\"   required>\r\n");
        out.write("\t\t\t\t\t\t\t              </div>\r\n");
        out.write("\t\t\t\t\t\t\t            \r\n");
        out.write("\t\t\t\t\t\t\t          </div>\r\n");
        out.write("\t\t\t\t\t\t\t          \r\n");
        out.write("\t\t\t\t\t\t\t              \r\n");
        out.write("\t\t\t\t\t\t\t          </div>\r\n");
        out.write("\t\t\t\t\t\t\t          \r\n");
        out.write("\t\t\t\t\t\t\t          \r\n");
        out.write("\t\t\t\t\t\t\t          \r\n");
        out.write("\t\t\t\t\t\t\t          <div class=\"row\">\r\n");
        out.write("\t\t\t\t\t\t\t          \r\n");
        out.write("\t\t\t\t\t\t\t          <div class=\"col-md-6\">\r\n");
        out.write("\t\t\t\t\t\t\t          <div class=\"form-group\">\r\n");
        out.write("\t\t\t\t\t\t\t                <label>Mobile No</label>\r\n");
        out.write("\t\t\t\t\t\t\t                <input type=\"text\" class=\"form-control\" value=\"");
        if (_jspx_meth_s_005fproperty_005f6(_jspx_th_s_005fpush_005f0, _jspx_page_context))
          return true;
        out.write("\" id=\"mobile\" name=\"mobile\" required >\r\n");
        out.write("\t\t\t\t\t\t\t              </div>\r\n");
        out.write("\t\t\t\t\t\t\t            \r\n");
        out.write("\t\t\t\t\t\t\t          </div>\r\n");
        out.write("\t\t\t\t\t\t\t          \r\n");
        out.write("\t\t\t\t\t\t\t          \r\n");
        out.write("\t\t\t\t\t\t\t          <div class=\"col-md-6\">\r\n");
        out.write("\t\t\t\t\t\t\t          <div class=\"form-group\">\r\n");
        out.write("\t\t\t\t\t\t\t                <label>GSTN No</label>\r\n");
        out.write("\t\t\t\t\t\t\t                <input type=\"text\" class=\"form-control\" value=\"");
        if (_jspx_meth_s_005fproperty_005f7(_jspx_th_s_005fpush_005f0, _jspx_page_context))
          return true;
        out.write("\" name=\"gstn\" id=\"gstn\"   required>\r\n");
        out.write("\t\t\t\t\t\t\t              </div>\r\n");
        out.write("\t\t\t\t\t\t\t            \r\n");
        out.write("\t\t\t\t\t\t\t          </div>\r\n");
        out.write("\t\t\t\t\t\t\t          \r\n");
        out.write("\t\t\t\t\t\t\t              \r\n");
        out.write("\t\t\t\t\t\t\t          </div>\r\n");
        out.write("\t\t\t\t\t\t\t          \r\n");
        out.write("\t\t\t\t\t\t\t          \r\n");
        out.write("\t\t\t\t\t\t\t          \r\n");
        out.write("\t\t\t\t\t\t\t          <div class=\"row\">\r\n");
        out.write("\t\t\t\t\t\t\t          \r\n");
        out.write("\t\t\t\t\t\t\t          <div class=\"col-md-6\">\r\n");
        out.write("\t\t\t\t\t\t\t          <div class=\"form-group\">\r\n");
        out.write("\t\t\t\t\t\t\t                <label>Bill To</label>\r\n");
        out.write("\t\t\t\t\t\t\t                <input type=\"text\" class=\"form-control\" id=\"destination\" value=\"");
        if (_jspx_meth_s_005fproperty_005f8(_jspx_th_s_005fpush_005f0, _jspx_page_context))
          return true;
        out.write("\" name=\"destination\" required >\r\n");
        out.write("\t\t\t\t\t\t\t              </div>\r\n");
        out.write("\t\t\t\t\t\t\t            \r\n");
        out.write("\t\t\t\t\t\t\t          </div>\r\n");
        out.write("\t\t\t\t\t\t\t          \r\n");
        out.write("\t\t\t\t\t\t\t          \r\n");
        out.write("\t\t\t\t\t\t\t          <div class=\"col-md-6\">\r\n");
        out.write("\t\t\t\t\t\t\t          <div class=\"form-group\">\r\n");
        out.write("\t\t\t\t\t\t\t                <label>Service Code</label>\r\n");
        out.write("\t\t\t\t\t\t\t                <input type=\"text\" class=\"form-control\"  name=\"source\" id=\"source\"   required>\r\n");
        out.write("\t\t\t\t\t\t\t              </div>\r\n");
        out.write("\t\t\t\t\t\t\t            \r\n");
        out.write("\t\t\t\t\t\t\t          </div>\r\n");
        out.write("\t\t\t\t\t\t\t          \r\n");
        out.write("\t\t\t\t\t\t\t              \r\n");
        out.write("\t\t\t\t\t\t\t          </div>\r\n");
        out.write("\t\t\t\t\t\t\t          \r\n");
        out.write("\t\t\t\t\t\t\t          \r\n");
        out.write("\t\t\t\t\t\t\t          \r\n");
        out.write("\t\t\t\t\t\t\t          <div class=\"row\">\r\n");
        out.write("\t\t\t\t\t\t\t          \r\n");
        out.write("\t\t\t\t\t\t\t          <div class=\"col-md-6\">\r\n");
        out.write("\t\t\t\t\t\t\t          <div class=\"form-group\">\r\n");
        out.write("\t\t\t\t\t\t\t                <label>Job No</label>\r\n");
        out.write("\t\t\t\t\t\t\t                <input type=\"text\" class=\"form-control\" id=\"job_no\" name=\"job_no\" required >\r\n");
        out.write("\t\t\t\t\t\t\t              </div>\r\n");
        out.write("\t\t\t\t\t\t\t            \r\n");
        out.write("\t\t\t\t\t\t\t          </div>\r\n");
        out.write("\t\t\t\t\t\t\t          \r\n");
        out.write("\t\t\t\t\t\t\t          <div class=\"col-md-6\">\r\n");
        out.write("\t\t\t\t\t\t\t          <div class=\"form-group\">\r\n");
        out.write("\t\t\t\t\t\t\t                <label>LR Amount</label>\r\n");
        out.write("\t\t\t\t\t\t\t                <input type=\"text\" class=\"form-control\" id=\"lr_amount\" name=\"lr_amount\" onblur=\"totalQty(this)\" required  >\r\n");
        out.write("\t\t\t\t\t\t\t              </div>\r\n");
        out.write("\t\t\t\t\t\t\t            \r\n");
        out.write("\t\t\t\t\t\t\t          </div>\r\n");
        out.write("\t\t\t\t\t\t\t          \r\n");
        out.write("\t\t\t\t\t\t\t              ");
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t          </div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t <div class=\"row\">\r\n");
        out.write("\t\t\t\t\t\t\t          \r\n");
        out.write("\t\t\t\t\t\t\t          <div class=\"col-md-6\">\r\n");
        out.write("\t\t\t\t\t\t\t          <div class=\"form-group\">\r\n");
        out.write("\t\t\t\t\t\t\t                <label>Contact Person</label>\r\n");
        out.write("\t\t\t\t\t\t\t                <input type=\"text\" class=\"form-control\" id=\"buyer_contact_person\" name=\"buyer_contact_person\" required >\r\n");
        out.write("\t\t\t\t\t\t\t              </div>\r\n");
        out.write("\t\t\t\t\t\t\t            \r\n");
        out.write("\t\t\t\t\t\t\t          </div>\r\n");
        out.write("\t\t\t\t\t\t\t          \r\n");
        out.write("\t\t\t\t\t\t\t          <div class=\"col-md-6\">\r\n");
        out.write("\t\t\t\t\t\t\t          <div class=\"form-group\">\r\n");
        out.write("\t\t\t\t\t\t\t                <label>Contact Person No</label>\r\n");
        out.write("\t\t\t\t\t\t\t                <input type=\"text\" class=\"form-control\" id=\"buyer_contact_no\" name=\"buyer_contact_no\" onblur=\"totalQty(this)\" required  >\r\n");
        out.write("\t\t\t\t\t\t\t              </div>\r\n");
        out.write("\t\t\t\t\t\t\t            \r\n");
        out.write("\t\t\t\t\t\t\t          </div>\r\n");
        out.write("\t\t\t\t\t\t\t          \r\n");
        out.write("\t\t\t\t\t\t\t              ");
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t          </div>\r\n");
        out.write("\t\t\t\t\t\t\t          \r\n");
        out.write("\t\t\t\t\t\t\t          <div class=\"row\">\r\n");
        out.write("\t\t\t\t\t\t\t          \r\n");
        out.write("\t\t\t\t\t\t\t          <div class=\"col-md-6\">\r\n");
        out.write("\t\t\t\t\t\t\t          <div class=\"form-group\">\r\n");
        out.write("\t\t\t\t\t\t\t                <label>Payment Terms</label>\r\n");
        out.write("\t\t\t\t\t\t\t                <input type=\"text\" class=\"form-control\" id=\"payterm\" name=\"payterm\" required >\r\n");
        out.write("\t\t\t\t\t\t\t              </div>\r\n");
        out.write("\t\t\t\t\t\t\t            \r\n");
        out.write("\t\t\t\t\t\t\t          </div>\r\n");
        out.write("\t\t\t\t\t\t\t          \r\n");
        out.write("\t\t\t\t\t\t\t          <div class=\"col-md-6\">\r\n");
        out.write("\t\t\t\t\t\t\t          <div class=\"form-group\">\r\n");
        out.write("\t\t\t\t\t\t\t                \r\n");
        out.write("&nbsp;\t\t\t\t\t\t\t              </div>\r\n");
        out.write("\t\t\t\t\t\t\t            \r\n");
        out.write("\t\t\t\t\t\t\t          </div>\r\n");
        out.write("\t\t\t\t\t\t\t          \r\n");
        out.write("\t\t\t\t\t\t\t              ");
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t          </div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<div id=\"product\" class=\"tab-pane table-responsive active\">\r\n");
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t<table id=\"itemsTable$\" class=\"table table-striped table-bordered\" cellspacing=\"0\" width=\"100%\">\r\n");
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<tbody>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<th id=\"VLsparename\" ><label>LR NO</label></th>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<th id=\"VLsparename\" ><label>Manual NO</label></th>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<th id=\"VLsparename\" ><label>DATE</label></th>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<th id=\"VLsparename\" ><label>CONSIGNOR</label></th>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<th id=\"VLsparename\" ><label>CONSIGNEE</label></th>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<th id=\"VLsparename\" ><label>FROM</label></th>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<th id=\"VLsparename\" ><label>To</label></th>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<th id=\"VLsparename\" ><label>CH WEIGHT</label></th>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<!-- <th id=\"VLsparename\" ><label>RATE</label></th>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t --><th id=\"VLsparename\" ><label>AMOUNT</label></th>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t</tbody>\r\n");
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t");
        if (_jspx_meth_s_005fiterator_005f0(_jspx_th_s_005fpush_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\r\n");
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t</table>\r\n");
        out.write("\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t \t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t");
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t          \r\n");
        out.write("\t\t\t\t\t\t\t          <div class=\"row\">\r\n");
        out.write("\t\t\t\t\t\t\t          \r\n");
        out.write("\t\t\t\t\t\t\t          \r\n");
        out.write("\t\t\t\t\t\t\t          <div class=\"col-md-6\">\r\n");
        out.write("\t\t\t\t\t\t\t          <div class=\"form-group\">\r\n");
        out.write("\t\t\t\t\t\t\t                <label>Total </label>\r\n");
        out.write("\t\t\t\t\t\t\t                <input type=\"hidden\" class=\"form-control\"   name=\"total\" id=\"total\"  readonly >\r\n");
        out.write("\t\t\t\t\t\t\t                   <input type=\"text\" class=\"form-control\"   name=\"total12\" id=\"total12\" readonly >\r\n");
        out.write("\t\t\t\t\t\t\t                 ");
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t                   \r\n");
        out.write("\t\t\t\t\t\t\t              </div>\r\n");
        out.write("\t\t\t\t\t\t\t            \r\n");
        out.write("\t\t\t\t\t\t\t          </div>\r\n");
        out.write("\t\t\t\t\t\t\t          \r\n");
        out.write("\t\t\t\t\t\t\t              \r\n");
        out.write("\t\t\t\t\t\t\t          </div>\r\n");
        out.write("\t\t\t\t\t\t\t          </div>\r\n");
        out.write("\t\t\t\t\t\t\t         \r\n");
        out.write("\t\t\t\t\t\t\t        \r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"panel-footer\" >\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-9 col-sm-offset-3\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-success btn-labeled fa fa-check fa-lg\" style=\"margin-left: 10px\" type=\"submit\" id=\"myBtn\" >Submit</button>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-danger btn-labeled fa fa-mail-reply fa-lg\" style=\"margin-left: 10px\" type=\"reset\"  onclick=\"history.go(-1)\">Back</button>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-primary btn-labeled fa fa-repeat fa-lg\" style=\"margin-left: 10px\" type=\"reset\">Reset</button>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t     </div>\r\n");
        out.write("\t\t\t\t\t\t\t\t</form>");
        int evalDoAfterBody = _jspx_th_s_005fpush_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_s_005fpush_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_s_005fpush_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fpush_0026_005fvalue.reuse(_jspx_th_s_005fpush_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fpush_0026_005fvalue.reuse(_jspx_th_s_005fpush_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fpush_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f0 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fpush_005f0);
    // /pages/form/CommonInvoice.jsp(159,70) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f0.setValue("name");
    int _jspx_eval_s_005fproperty_005f0 = _jspx_th_s_005fproperty_005f0.doStartTag();
    if (_jspx_th_s_005fproperty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fpush_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f1 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f1.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fpush_005f0);
    // /pages/form/CommonInvoice.jsp(161,71) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f1.setValue("customer_no");
    int _jspx_eval_s_005fproperty_005f1 = _jspx_th_s_005fproperty_005f1.doStartTag();
    if (_jspx_th_s_005fproperty_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f1);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fpush_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f2 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f2.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fpush_005f0);
    // /pages/form/CommonInvoice.jsp(162,70) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f2.setValue("inquiry_id");
    int _jspx_eval_s_005fproperty_005f2 = _jspx_th_s_005fproperty_005f2.doStartTag();
    if (_jspx_th_s_005fproperty_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f2);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fpush_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f3 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f3.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fpush_005f0);
    // /pages/form/CommonInvoice.jsp(172,70) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f3.setValue("invoiceno");
    int _jspx_eval_s_005fproperty_005f3 = _jspx_th_s_005fproperty_005f3.doStartTag();
    if (_jspx_th_s_005fproperty_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f3);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fpush_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f4 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f4.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fpush_005f0);
    // /pages/form/CommonInvoice.jsp(187,70) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f4.setValue("address");
    int _jspx_eval_s_005fproperty_005f4 = _jspx_th_s_005fproperty_005f4.doStartTag();
    if (_jspx_th_s_005fproperty_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f4);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fpush_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f5 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f5.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fpush_005f0);
    // /pages/form/CommonInvoice.jsp(196,93) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f5.setValue("date");
    int _jspx_eval_s_005fproperty_005f5 = _jspx_th_s_005fproperty_005f5.doStartTag();
    if (_jspx_th_s_005fproperty_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f5);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fpush_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f6 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f6.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fpush_005f0);
    // /pages/form/CommonInvoice.jsp(211,70) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f6.setValue("mobile");
    int _jspx_eval_s_005fproperty_005f6 = _jspx_th_s_005fproperty_005f6.doStartTag();
    if (_jspx_th_s_005fproperty_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f6);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f6);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fpush_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f7 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f7.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fpush_005f0);
    // /pages/form/CommonInvoice.jsp(220,70) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f7.setValue("gstn");
    int _jspx_eval_s_005fproperty_005f7 = _jspx_th_s_005fproperty_005f7.doStartTag();
    if (_jspx_th_s_005fproperty_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f7);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f7);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f8(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fpush_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f8 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f8.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f8.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fpush_005f0);
    // /pages/form/CommonInvoice.jsp(235,87) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f8.setValue("bill_to");
    int _jspx_eval_s_005fproperty_005f8 = _jspx_th_s_005fproperty_005f8.doStartTag();
    if (_jspx_th_s_005fproperty_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f8);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f8);
    return false;
  }

  private boolean _jspx_meth_s_005fiterator_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fpush_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:iterator
    org.apache.struts2.views.jsp.IteratorTag _jspx_th_s_005fiterator_005f0 = (org.apache.struts2.views.jsp.IteratorTag) _005fjspx_005ftagPool_005fs_005fiterator_0026_005fvalue_005fstatus.get(org.apache.struts2.views.jsp.IteratorTag.class);
    _jspx_th_s_005fiterator_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fiterator_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fpush_005f0);
    // /pages/form/CommonInvoice.jsp(341,8) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fiterator_005f0.setValue("(gridsize).{# this}");
    // /pages/form/CommonInvoice.jsp(341,8) name = status type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fiterator_005f0.setStatus("stat");
    int _jspx_eval_s_005fiterator_005f0 = _jspx_th_s_005fiterator_005f0.doStartTag();
    if (_jspx_eval_s_005fiterator_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_s_005fiterator_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_s_005fiterator_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_s_005fiterator_005f0.doInitBody();
      }
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<tr class=\"item-row\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<td><input class=\"form-control\" style=\"width:120px;\"  type=\"text\" name=\"aa\"  \r\n");
        out.write("\t\t\t\t\t\t\t\t\tid=\"aa\" value=\"");
        if (_jspx_meth_s_005fproperty_005f9(_jspx_th_s_005fiterator_005f0, _jspx_page_context))
          return true;
        out.write("\" readonly/></td>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<td><input class=\"form-control\" style=\"width:120px;\"  type=\"text\" name=\"hh\"  \r\n");
        out.write("\t\t\t\t\t\t\t\t\tid=\"hh\" value=\"");
        if (_jspx_meth_s_005fproperty_005f10(_jspx_th_s_005fiterator_005f0, _jspx_page_context))
          return true;
        out.write("\" /></td>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<td><input class=\"form-control\" style=\"width:120px;\"  type=\"text\" name=\"bb\"  \r\n");
        out.write("\t\t\t\t\t\t\t\t\tid=\"bb\" value=\"");
        if (_jspx_meth_s_005fproperty_005f11(_jspx_th_s_005fiterator_005f0, _jspx_page_context))
          return true;
        out.write("\" readonly/></td>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<td><input class=\"form-control\" style=\"width:120px;\"  type=\"text\" name=\"cc\"  \r\n");
        out.write("\t\t\t\t\t\t\t\t\tid=\"cc\" value=\"");
        if (_jspx_meth_s_005fproperty_005f12(_jspx_th_s_005fiterator_005f0, _jspx_page_context))
          return true;
        out.write("\" readonly/></td>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<td><input class=\"form-control\" style=\"width:120px;\"  type=\"text\" name=\"dd\"  \r\n");
        out.write("\t\t\t\t\t\t\t\t\tid=\"dd\" value=\"");
        if (_jspx_meth_s_005fproperty_005f13(_jspx_th_s_005fiterator_005f0, _jspx_page_context))
          return true;
        out.write("\" readonly/></td>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<td><input class=\"form-control\" style=\"width:120px;\"  type=\"text\" name=\"ee\"  \r\n");
        out.write("\t\t\t\t\t\t\t\t\tid=\"ee\" value=\"");
        if (_jspx_meth_s_005fproperty_005f14(_jspx_th_s_005fiterator_005f0, _jspx_page_context))
          return true;
        out.write("\" readonly/></td>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<td><input class=\"form-control\" style=\"width:120px;\"  type=\"text\" name=\"ff\"  \r\n");
        out.write("\t\t\t\t\t\t\t\t\tid=\"ff\" value=\"");
        if (_jspx_meth_s_005fproperty_005f15(_jspx_th_s_005fiterator_005f0, _jspx_page_context))
          return true;
        out.write("\" readonly/></td>\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<td><input class=\"form-control\" style=\"width:80px;\"  type=\"text\" name=\"gg\"  \r\n");
        out.write("\t\t\t\t\t\t\t\t\tid=\"gg\" value=\"");
        if (_jspx_meth_s_005fproperty_005f16(_jspx_th_s_005fiterator_005f0, _jspx_page_context))
          return true;
        out.write("\" required/></td>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<!-- <td><input class=\"form-control\" style=\"width:80px;\"  type=\"text\" name=\"hh\"  \r\n");
        out.write("\t\t\t\t\t\t\t\t\tid=\"hh\" onblur=\"getAmount(this);totalQty(this);\" required/></td>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t -->\r\n");
        out.write("\t\t\t\t\t\t\t\t\t \r\n");
        out.write("\t\t\t\t\t\t\t\t\t ");
        if (_jspx_meth_s_005fif_005f0(_jspx_th_s_005fiterator_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t");
        if (_jspx_meth_s_005felse_005f0(_jspx_th_s_005fiterator_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
        out.write("\t\t\t\t\t\t\t\t\r\n");
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_s_005fiterator_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_s_005fiterator_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_s_005fiterator_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fiterator_0026_005fvalue_005fstatus.reuse(_jspx_th_s_005fiterator_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fiterator_0026_005fvalue_005fstatus.reuse(_jspx_th_s_005fiterator_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f9(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fiterator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f9 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f9.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f9.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fiterator_005f0);
    // /pages/form/CommonInvoice.jsp(345,24) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f9.setValue("dcnot[top]");
    int _jspx_eval_s_005fproperty_005f9 = _jspx_th_s_005fproperty_005f9.doStartTag();
    if (_jspx_th_s_005fproperty_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f9);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f9);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f10(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fiterator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f10 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f10.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f10.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fiterator_005f0);
    // /pages/form/CommonInvoice.jsp(349,24) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f10.setValue("dcnot[top]");
    int _jspx_eval_s_005fproperty_005f10 = _jspx_th_s_005fproperty_005f10.doStartTag();
    if (_jspx_th_s_005fproperty_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f10);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f10);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f11(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fiterator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f11 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f11.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f11.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fiterator_005f0);
    // /pages/form/CommonInvoice.jsp(352,24) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f11.setValue("descriptiont[top]");
    int _jspx_eval_s_005fproperty_005f11 = _jspx_th_s_005fproperty_005f11.doStartTag();
    if (_jspx_th_s_005fproperty_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f11);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f11);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f12(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fiterator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f12 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f12.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f12.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fiterator_005f0);
    // /pages/form/CommonInvoice.jsp(355,24) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f12.setValue("quantityt[top]");
    int _jspx_eval_s_005fproperty_005f12 = _jspx_th_s_005fproperty_005f12.doStartTag();
    if (_jspx_th_s_005fproperty_005f12.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f12);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f12);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f13(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fiterator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f13 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f13.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f13.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fiterator_005f0);
    // /pages/form/CommonInvoice.jsp(358,24) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f13.setValue("myrate[top]");
    int _jspx_eval_s_005fproperty_005f13 = _jspx_th_s_005fproperty_005f13.doStartTag();
    if (_jspx_th_s_005fproperty_005f13.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f13);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f13);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f14(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fiterator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f14 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f14.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f14.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fiterator_005f0);
    // /pages/form/CommonInvoice.jsp(361,24) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f14.setValue("hsncode[top]");
    int _jspx_eval_s_005fproperty_005f14 = _jspx_th_s_005fproperty_005f14.doStartTag();
    if (_jspx_th_s_005fproperty_005f14.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f14);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f14);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f15(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fiterator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f15 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f15.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f15.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fiterator_005f0);
    // /pages/form/CommonInvoice.jsp(364,24) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f15.setValue("rate[top]");
    int _jspx_eval_s_005fproperty_005f15 = _jspx_th_s_005fproperty_005f15.doStartTag();
    if (_jspx_th_s_005fproperty_005f15.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f15);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f15);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f16(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fiterator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f16 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f16.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f16.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fiterator_005f0);
    // /pages/form/CommonInvoice.jsp(368,24) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f16.setValue("bank22[top]");
    int _jspx_eval_s_005fproperty_005f16 = _jspx_th_s_005fproperty_005f16.doStartTag();
    if (_jspx_th_s_005fproperty_005f16.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f16);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f16);
    return false;
  }

  private boolean _jspx_meth_s_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fiterator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:if
    org.apache.struts2.views.jsp.IfTag _jspx_th_s_005fif_005f0 = (org.apache.struts2.views.jsp.IfTag) _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.get(org.apache.struts2.views.jsp.IfTag.class);
    _jspx_th_s_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fiterator_005f0);
    // /pages/form/CommonInvoice.jsp(374,10) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fif_005f0.setTest("#session.USER_PROFILE.type=='Admin'");
    int _jspx_eval_s_005fif_005f0 = _jspx_th_s_005fif_005f0.doStartTag();
    if (_jspx_eval_s_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_s_005fif_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_s_005fif_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_s_005fif_005f0.doInitBody();
      }
      do {
        out.write(" \r\n");
        out.write("\t\t\t\t\t\t\t\t\t \r\n");
        out.write("\t\t\t\t\t\t\t\t\t<td><input class=\"form-control\" style=\"width:80px;\"  type=\"text\" name=\"ii\"  \r\n");
        out.write("\t\t\t\t\t\t\t\t\tid=\"ii\" value=\"");
        if (_jspx_meth_s_005fproperty_005f17(_jspx_th_s_005fif_005f0, _jspx_page_context))
          return true;
        out.write("\" onblur=\"totalQty(this)\" required  /></td>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_s_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_s_005fif_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_s_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.reuse(_jspx_th_s_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.reuse(_jspx_th_s_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f17(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f17 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f17.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f17.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fif_005f0);
    // /pages/form/CommonInvoice.jsp(377,24) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f17.setValue("totalamt[top]");
    int _jspx_eval_s_005fproperty_005f17 = _jspx_th_s_005fproperty_005f17.doStartTag();
    if (_jspx_th_s_005fproperty_005f17.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f17);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f17);
    return false;
  }

  private boolean _jspx_meth_s_005felse_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fiterator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:else
    org.apache.struts2.views.jsp.ElseTag _jspx_th_s_005felse_005f0 = (org.apache.struts2.views.jsp.ElseTag) _005fjspx_005ftagPool_005fs_005felse.get(org.apache.struts2.views.jsp.ElseTag.class);
    _jspx_th_s_005felse_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005felse_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fiterator_005f0);
    int _jspx_eval_s_005felse_005f0 = _jspx_th_s_005felse_005f0.doStartTag();
    if (_jspx_eval_s_005felse_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_s_005felse_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_s_005felse_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_s_005felse_005f0.doInitBody();
      }
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<td><input class=\"form-control\" style=\"width:80px;\"  type=\"text\" name=\"ii\"  \r\n");
        out.write("\t\t\t\t\t\t\t\t\tid=\"ii\" value=\"");
        if (_jspx_meth_s_005fproperty_005f18(_jspx_th_s_005felse_005f0, _jspx_page_context))
          return true;
        out.write("\" required  readonly/></td>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_s_005felse_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_s_005felse_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_s_005felse_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005felse.reuse(_jspx_th_s_005felse_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005felse.reuse(_jspx_th_s_005felse_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f18(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005felse_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f18 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f18.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f18.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005felse_005f0);
    // /pages/form/CommonInvoice.jsp(383,24) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f18.setValue("totalamt[top]");
    int _jspx_eval_s_005fproperty_005f18 = _jspx_th_s_005fproperty_005f18.doStartTag();
    if (_jspx_th_s_005fproperty_005f18.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f18);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f18);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f19(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f19 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f19.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f19.setParent(null);
    // /pages/form/CommonInvoice.jsp(605,117) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f19.setValue("lrno[top]");
    int _jspx_eval_s_005fproperty_005f19 = _jspx_th_s_005fproperty_005f19.doStartTag();
    if (_jspx_th_s_005fproperty_005f19.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f19);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f19);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f20(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f20 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f20.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f20.setParent(null);
    // /pages/form/CommonInvoice.jsp(607,130) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f20.setValue("drivername[top]");
    int _jspx_eval_s_005fproperty_005f20 = _jspx_th_s_005fproperty_005f20.doStartTag();
    if (_jspx_th_s_005fproperty_005f20.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f20);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f20);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f21(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f21 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f21.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f21.setParent(null);
    // /pages/form/CommonInvoice.jsp(609,125) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f21.setValue("expdate[top]");
    int _jspx_eval_s_005fproperty_005f21 = _jspx_th_s_005fproperty_005f21.doStartTag();
    if (_jspx_th_s_005fproperty_005f21.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f21);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f21);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f22(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f22 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f22.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f22.setParent(null);
    // /pages/form/CommonInvoice.jsp(611,125) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f22.setValue("exppart1[top]");
    int _jspx_eval_s_005fproperty_005f22 = _jspx_th_s_005fproperty_005f22.doStartTag();
    if (_jspx_th_s_005fproperty_005f22.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f22);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f22);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f23(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f23 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f23.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f23.setParent(null);
    // /pages/form/CommonInvoice.jsp(613,123) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f23.setValue("expamt[top]");
    int _jspx_eval_s_005fproperty_005f23 = _jspx_th_s_005fproperty_005f23.doStartTag();
    if (_jspx_th_s_005fproperty_005f23.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f23);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f23);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f24(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f24 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f24.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f24.setParent(null);
    // /pages/form/CommonInvoice.jsp(615,130) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f24.setValue("drivername[top]");
    int _jspx_eval_s_005fproperty_005f24 = _jspx_th_s_005fproperty_005f24.doStartTag();
    if (_jspx_th_s_005fproperty_005f24.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f24);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f24);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f25(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f25 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f25.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f25.setParent(null);
    // /pages/form/CommonInvoice.jsp(617,125) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f25.setValue("expdate[top]");
    int _jspx_eval_s_005fproperty_005f25 = _jspx_th_s_005fproperty_005f25.doStartTag();
    if (_jspx_th_s_005fproperty_005f25.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f25);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f25);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f26(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f26 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f26.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f26.setParent(null);
    // /pages/form/CommonInvoice.jsp(619,125) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f26.setValue("exppart1[top]");
    int _jspx_eval_s_005fproperty_005f26 = _jspx_th_s_005fproperty_005f26.doStartTag();
    if (_jspx_th_s_005fproperty_005f26.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f26);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f26);
    return false;
  }
}
