/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2024-03-11 11:29:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages.form;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class CustomerPayment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1542635938000L));
    _jspx_dependants.put("jar:file:/E:/WORKSPACE/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HSL031220/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098691290000L));
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.2.1.jar", Long.valueOf(1542635950000L));
    _jspx_dependants.put("jar:file:/E:/WORKSPACE/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HSL031220/WEB-INF/lib/struts2-core-2.2.1.jar!/META-INF/struts-tags.tld", Long.valueOf(1279356888000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fform_0026_005ftheme_005fonsubmit_005fid_005fclass_005faction;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fs_005fform_0026_005ftheme_005fonsubmit_005fid_005fclass_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fs_005fform_0026_005ftheme_005fonsubmit_005fid_005fclass_005faction.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no\"\r\n");
      out.write("\tname=\"viewport\">\r\n");
      out.write("<script src=\"Css/jquery-1.10.2.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"Css/jquery-ui.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Css/validationEngine/validationEngine.jquery.css\" type=\"text/css\" />\r\n");
      out.write("<script src=\"js/languages/jquery.validationEngine-en.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("<script src=\"js/jquery.validationEngine.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Css/validationEngine.jquery.css\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("<script src=\"jQuery_4_design/AutoSearch/AutoSearchJquerySale.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"datevalidation.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\" language=\"javascript\" src=\"js/rptsTable/jquery.dataTables.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" media=\"all\" href=\"Css/AutoSearch/styleAS.css\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"Css/styleAS.css\" />\r\n");
      out.write("<script src=\"js/jquery-migrate-1.2.1.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function showWithGrid() {\r\n");
      out.write("\t\r\n");
      out.write("\tvar withgrid=document.getElementById(\"withgrid\").value;\r\n");
      out.write("\t\r\n");
      out.write("\talert(withgrid);\r\n");
      out.write("\t\r\n");
      out.write("\tdocument.getElementById(\"WithGrid\").value=withgrid;\r\n");
      out.write("\t\r\n");
      out.write("\tif(document.getElementById(\"withgrid\").checked==true){\r\n");
      out.write("\t\tdocument.getElementById(\"withoutgrid\").checked=false;\r\n");
      out.write("\t\tdocument.getElementById(\"customer_name_id\").style.display=\"block\";\r\n");
      out.write("\t\tdocument.getElementById(\"customer_grid_id\").style.display=\"block\";\r\n");
      out.write("\t\tdocument.getElementById(\"direct_customer_name\").style.display=\"none\";\r\n");
      out.write("\t\tdocument.getElementById(\"dealer_payment_amt\").readOnly = true;\r\n");
      out.write("\t\tdocument.getElementById(\"dealer_code\").focus();\r\n");
      out.write("\t\tdocument.getElementById(\"dealer_payment_amt\").value=\"\";\r\n");
      out.write("\t}else\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\tdocument.getElementById(\"customer_name_id\").style.display=\"none\";\r\n");
      out.write("\t\tdocument.getElementById(\"customer_grid_id\").style.display=\"none\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function showwithoutGrid() {\r\n");
      out.write("\t\r\n");
      out.write("\tvar withoutgrid=document.getElementById(\"withoutgrid\").value;\r\n");
      out.write("\t\r\n");
      out.write("\talert(withoutgrid);\r\n");
      out.write("\t\r\n");
      out.write("\tdocument.getElementById(\"WithoutGrid\").value=withoutgrid;\r\n");
      out.write("\t\r\n");
      out.write("\tif(document.getElementById(\"withoutgrid\").checked==true)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.getElementById(\"withgrid\").checked=false;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdocument.getElementById(\"customer_name_id\").style.display=\"none\";\r\n");
      out.write("\t\tdocument.getElementById(\"direct_customer_name\").style.display=\"block\";\r\n");
      out.write("\t\tdocument.getElementById(\"customer_grid_id\").style.display=\"none\";\r\n");
      out.write("\t\tdocument.getElementById(\"dealer_payment_amt\").readOnly = false;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar total_amount=document.getElementById(\"total_amount\").value;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdocument.getElementById(\"dealer_payment_amt\").value=total_amount;\r\n");
      out.write("\t\tdocument.getElementById(\"dealer_payment_amt\").focus();\r\n");
      out.write("\t\t\r\n");
      out.write("\t}else\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tdocument.getElementById(\"customer_name_id\").style.display=\"none\";\r\n");
      out.write("\t\t}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\tfunction display(obj) {\r\n");
      out.write("\t\talert(obj);\r\n");
      out.write("\t\ttxt = obj.options[obj.selectedIndex].value;\r\n");
      out.write("\t\t$(\"#1\").hide();\r\n");
      out.write("\t\t$(\"#2\").hide();\r\n");
      out.write("\t\t$(\"#3\").hide();\r\n");
      out.write("\t\t$(\"#4\").hide();\r\n");
      out.write("\t\t$(\"#5\").hide();\r\n");
      out.write("\t\t$(\"#6\").hide();\r\n");
      out.write("\t\t$(\"#7\").hide();\r\n");
      out.write("\t\t$(\"#7x\").hide();\r\n");
      out.write("\t\t$(\"#8\").hide();\r\n");
      out.write("\t\t$(\"#tab\").hide();\r\n");
      out.write("\t\t$(\"#22\").hide();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdocument.getElementById(\"p4\").required = false;\r\n");
      out.write("\t\tdocument.getElementById(\"p5\").required = false;\r\n");
      out.write("\t\tdocument.getElementById(\"p6\").required = false;\r\n");
      out.write("\t\tdocument.getElementById(\"bankname\").required = false;\r\n");
      out.write("\t\tdocument.getElementById(\"transcation_id\").required = false;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (txt == 1) {\r\n");
      out.write("\t\t\t$(\"#1\").show(1000);\r\n");
      out.write("\t\t\t$(\"#tab\").show(1000);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (txt == 2) {\r\n");
      out.write("\t\t\t$(\"#1\").show(1000);\r\n");
      out.write("\t\t\t$(\"#2\").show(1000);\r\n");
      out.write("\t\t\t$(\"#3\").show(1000);\r\n");
      out.write("\t\t\t$(\"#4\").show(1000);\r\n");
      out.write("\t\t\t$(\"#5\").show(1000);\r\n");
      out.write("\t\t\t$(\"#6\").show(1000);\r\n");
      out.write("\t\t\t$(\"#tab\").show(1000);\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (txt == 3) {\r\n");
      out.write("\t\t\t$(\"#1\").show(1000);\r\n");
      out.write("\t\t\t$(\"#2\").show(1000);\r\n");
      out.write("\t\t\t$(\"#3\").show(1000);\r\n");
      out.write("\t\t\t$(\"#4\").show(1000);\r\n");
      out.write("\t\t\t$(\"#22\").show(1000);\r\n");
      out.write("\t\t\t$(\"#tab\").show(1000);\r\n");
      out.write("\t\t\tdocument.getElementById(\"p4\").required = true;\r\n");
      out.write("\t\t\tdocument.getElementById(\"p5\").required = true;\r\n");
      out.write("\t\t\tdocument.getElementById(\"p6\").required = true;\r\n");
      out.write("\t\t\tdocument.getElementById(\"bankname\").required = true;\r\n");
      out.write("\t\t\tdocument.getElementById(\"bankname22\").required = true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (txt == 4) {\r\n");
      out.write("\t\t\t$(\"#2\").show(1000);\r\n");
      out.write("\t\t\t$(\"#1\").show(1000);\r\n");
      out.write("\t\t\t$(\"#7\").show(1000);\r\n");
      out.write("\t\t\t$(\"#tab\").show(1000);\r\n");
      out.write("\t\t\t$(\"#22\").show(1000);\r\n");
      out.write("\t\t\tdocument.getElementById(\"bankname\").required = true;\r\n");
      out.write("\t\t\tdocument.getElementById(\"transcation_id\").required = true;\r\n");
      out.write("\t\t\tdocument.getElementById(\"bankname22\").required = true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (txt == 5) {\r\n");
      out.write("\t\t\t$(\"#1\").show(1000);\r\n");
      out.write("\t\t\t$(\"#7\").show(1000);\r\n");
      out.write("\t\t\t$(\"#7x\").show(1000);\r\n");
      out.write("\t\t\t$(\"#tab\").show(1000);\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (txt == 6) {\r\n");
      out.write("\t\t\t$(\"#1\").show(1000);\r\n");
      out.write("\t\t\t$(\"#7\").show(1000);\r\n");
      out.write("\t\t\t$(\"#tab\").show(1000);\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\tfunction f1()\r\n");
      out.write("\t{\r\n");
      out.write("\t\t\r\n");
      out.write("    var x=document.getElementById(\"dealer_payment_amt\").value;\r\n");
      out.write("          document.getElementById(\"net_amount\").value=x;\r\n");
      out.write("          document.getElementById(\"p5\").value=x;\r\n");
      out.write("          \r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(function() {\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#dealer_code\").autocomplete(\"GoogleSearch/cust_auto_search.jsp\");\r\n");
      out.write("\t$(\"#empcode\").autocomplete(\"GoogleSearch/emp_code_auto_search.jsp\");\t\r\n");
      out.write("\t$(\"#icr_no\").autocomplete(\"GoogleSearch/payment_Invoice_no_auto_search.jsp\");\r\n");
      out.write("\t$(\"#bankname\").autocomplete(\"GoogleSearch/bankmaster_auto_search.jsp\");\r\n");
      out.write("\t$(\"#bankname22\").autocomplete(\"GoogleSearch/bankmaster_auto_search.jsp\");\r\n");
      out.write("\t/* $(\"#product_code\").autocomplete(\"GoogleSearch/amc_productcode_auto_search.jsp\");\r\n");
      out.write("\t$(\"#unit_no\").autocomplete(\"GoogleSearch/amc_unitno_auto_search.jsp\");\r\n");
      out.write("\t$(\"#dealer_name\").autocomplete(\"GoogleSearch/dealer_name_search.jsp\"); */\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("$(function() {\r\n");
      out.write("\tvar today = new Date(); \r\n");
      out.write("\tvar dd = today.getDate(); \r\n");
      out.write("\tvar mm = today.getMonth()+1;//January is 0! \r\n");
      out.write("\tvar yyyy = today.getFullYear(); \r\n");
      out.write("\tif(dd<10){dd='0'+dd} \r\n");
      out.write("\tif(mm<10){mm='0'+mm} \r\n");
      out.write("\t$(\"#payment_date\").val(dd+'-'+mm+'-'+yyyy);\r\n");
      out.write("\t//$(\"#payment_date\").focus();\r\n");
      out.write("\t\t$(\"#dealerpayment\").validationEngine();\r\n");
      out.write("\t\t$(\"#s1\").hide();\r\n");
      out.write("\t\t$(\"#s2\").hide();\r\n");
      out.write("\t\t$(\"#s3\").hide();\r\n");
      out.write("\t\t$(\"#s4\").hide();\r\n");
      out.write("\t\t/* $(\"#payment_date\" ).datepicker();\r\n");
      out.write("\t\t\tdateFormat: \"dd-mm-yy\"\t; */\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("/* end */\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function showconfig(){\r\n");
      out.write("\t\r\n");
      out.write("\t\t//alert(\">>>>>1\");\r\n");
      out.write("\t\tvar aa=document.getElementById(\"dealer_code\").value;\r\n");
      out.write("\t\talert(aa);\r\n");
      out.write("\t\tvar parts=aa.split(\"-\");\r\n");
      out.write("\t\tvar autoinvoice = parts[1];\r\n");
      out.write("\t\talert(autoinvoice);\r\n");
      out.write("\t\t//var autoinvoice1 = document.getElementById(\"qtyy\").value;\r\n");
      out.write("\t\tif(aa!=\"\"){\r\n");
      out.write("\t\t if (window.XMLHttpRequest) {\r\n");
      out.write("\t\t\t\tvar xp1=new XMLHttpRequest();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse {\r\n");
      out.write("\t\t\t\tvar xp1=new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\txp1.open(\"POST\",\"InvoiceSearch1?autoinvoice=\"+autoinvoice);\r\n");
      out.write("\t//alert(\"FetchspareGatepassAssemblyform?autoinvoice=\"+inv);\r\n");
      out.write("\r\n");
      out.write("\t    xp1.send();\r\n");
      out.write("\r\n");
      out.write("\t   \r\n");
      out.write("\t   xp1.onreadystatechange=function() {\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\tif (xp1.readyState==4 && xp1.status==200) {\r\n");
      out.write("\r\n");
      out.write("\t//alert(xp1.responseText);\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\tdocument.getElementById(\"documentNoSpan\").innerHTML=xp1.responseText;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t \t  };\r\n");
      out.write("\t\t\r\n");
      out.write("\t \t \r\n");
      out.write("\t \t document.getElementById(\"editdiv\").style.height=\"auto\";\r\n");
      out.write("\t \t   \t  \r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\talert(\"Please select Customer Name\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t}    \r\n");
      out.write("\t    \r\n");
      out.write("    \r\n");
      out.write("  </script>  \r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write(" var k=1;\r\n");
      out.write(" $(document).ready(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("     $(\"#addRow\").bind('click', addRows);\r\n");
      out.write("function addRows(e){\r\n");
      out.write("               try{\r\n");
      out.write("               \r\n");
      out.write("               \tk++;\r\n");
      out.write("                         var $itemsTable = $('#itemsTable');  \r\n");
      out.write("                         var $row = $($rowTemp);\r\n");
      out.write("                         //alert(k);\r\n");
      out.write("                         var $rowTemp = [\r\n");
      out.write("                         '<tr class=\"item-row\">',\r\n");
      out.write("                         '<td><a id=\"deleteRow\"><img src=\"Images_4_design/AddRowDataTable/icon-minus.png\" alt=\"Remove Item\" title=\"Remove Item\"></a></td>',\r\n");
      out.write("                         /* '<td>'+k+'</td>', */\r\n");
      out.write("                       '<td><input  style=\"width:190px\" type=\"text\" name=\"material\"  size=\"30\"  id=\"material\"  maxlegth=\"400\"  Class=\"validate[required]\" /></td>',\r\n");
      out.write("                       '<td><input  style=\"width:80px\" type=\"text\" name=\"materialqty\" id=\"materialqty\"  maxlegth=\"20\"   Class=\"validate[required]\" /></td>',\r\n");
      out.write("                       '<td><input  style=\"width:80px\" type=\"text\" name=\"qty123\" id=\"qty123\"  maxlegth=\"20\"   Class=\"validate[required]\" /></td>',\r\n");
      out.write("                       '<td><input  style=\"width:80px\" type=\"text\" name=\"qty123\" id=\"qty123\"  maxlegth=\"20\"   Class=\"validate[required]\" /></td>',                          \r\n");
      out.write("                                '</tr>'\r\n");
      out.write("                         ].join('');\r\n");
      out.write("                         var $row = $($rowTemp);\r\n");
      out.write("                         $.currentRow = $row;    \r\n");
      out.write("                         var $pcode= $row.find('#material');\r\n");
      out.write("                         $($pcode).autocomplete(\"GoogleSearch/spare_name_master_auto_search.jsp\");\r\n");
      out.write("                         \r\n");
      out.write("                         $last = $('#itemsTable').find('tbody tr:last');\r\n");
      out.write("                         $.first = $last.find('input:first');\r\n");
      out.write("                         if (true ) {                       \t                                                   \t          \r\n");
      out.write("                    \t$('.item-row:last', $itemsTable).after($row);                    \t                     \r\n");
      out.write("                         }// End if last ItemName input is empty\r\n");
      out.write("                         else\r\n");
      out.write("                  \t\t {\r\n");
      out.write("                  \t\t $('.item-row:last', $itemsTable).after($row);                  \t\t                    \t      \r\n");
      out.write("                  \t\t }\r\n");
      out.write("                         $last = $('#itemsTable').find('tbody tr:last');\r\n");
      out.write("                         $.first = $last.find('input:first');\r\n");
      out.write("                         $($pcode).focus();\r\n");
      out.write("               }catch(err){\r\n");
      out.write("                         alert(err);\r\n");
      out.write("               }\r\n");
      out.write("               return false;\r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("}); // End DOM\r\n");
      out.write("\r\n");
      out.write("//Remove row when clicked\r\n");
      out.write("$(\"#deleteRow\").live('click',function(){\r\n");
      out.write("\t\r\n");
      out.write("     $(this).parents('.item-row').remove();\r\n");
      out.write("     // Hide delete Icon if we only have one row in the list.\r\n");
      out.write("     \r\n");
      out.write("     k--;\r\n");
      out.write("     if ($(\".item-row\").length < 2) $(\"#deleteRow\").hide();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("    $(\"#addRowSpare\").bind('click', addRows);\r\n");
      out.write("function addRows(e){\r\n");
      out.write("              try{\r\n");
      out.write("              \t\r\n");
      out.write("                        var $itemsTable = $('#itemsTableSpare');\r\n");
      out.write("                        var $rowTemp = [\r\n");
      out.write("                        '<tr class=\"item-row1\">',\r\n");
      out.write("                      \r\n");
      out.write("                        '<td><a id=\"deleteRow1\"><img src=\"Images_4_design/AddRowDataTable/icon-minus.png\" alt=\"Remove Item\" title=\"Remove Item\"></a></td>',\r\n");
      out.write("                        \r\n");
      out.write("                      \r\n");
      out.write("                       \r\n");
      out.write("                       '<td><input type=\"text\" name=\"prb.product_code\" id=\"product_code\" /></td>', \r\n");
      out.write("                       \r\n");
      out.write("                       '<td><Select name=\"prb.unitno\" id=\"unit_no\" ><option value=\"NOS\">NOS</option><option value=\"PCS\">PCS</option><option value=\"MTRS\">MTRS</option></Select></td>', \r\n");
      out.write("                     \r\n");
      out.write("                       '<td><input type=\"text\" name=\"prb.price2\" onblur=\"allnumeric(this);\" onchange=\"netamt();\" id=\"price2\" maxlength=\"4\" /></td>', \r\n");
      out.write("\r\n");
      out.write("                       \r\n");
      out.write("                       \r\n");
      out.write("                        '</tr>'\r\n");
      out.write("                        ].join('');\r\n");
      out.write("                        var $row = $($rowTemp);\r\n");
      out.write("                        $.currentRow = $row;\r\n");
      out.write("                       \r\n");
      out.write("                        var $row = $($rowTemp);\r\n");
      out.write("                        $.currentRow = $row;    \r\n");
      out.write("                        var $pcode= $row.find('#model');\r\n");
      out.write("                        $($pcode).autocomplete(\"GoogleSearch/model_auto_search_pc.jsp\");\r\n");
      out.write("                        $last = $('#itemsTable').find('tbody tr:last');\r\n");
      out.write("                        $.first = $last.find('input:first');\r\n");
      out.write("                        if (true ) {                       \t                                                   \t          \r\n");
      out.write("                   \t$('.item-row1:last', $itemsTable).after($row);                    \t                     \r\n");
      out.write("                        }// End if last ItemName input is empty\r\n");
      out.write("                        else\r\n");
      out.write("                 \t\t {\r\n");
      out.write("                 \t\t $('.item-row1:last', $itemsTable).after($row);                  \t\t                    \t      \r\n");
      out.write("                 \t\t }\r\n");
      out.write("                        $last = $('#itemsTable').find('tbody tr:last');\r\n");
      out.write("                        $.first = $last.find('input:first');\r\n");
      out.write("                        $($pcode).focus();\r\n");
      out.write("              }catch(err){\r\n");
      out.write("                        alert(err);\r\n");
      out.write("              }\r\n");
      out.write("              return false;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//    $('#ItemName').focus(function(){\r\n");
      out.write("//              window.onbeforeunload = function(){\r\n");
      out.write("//                        return \"You haven't saved your data.  Are you sure you want to leave this page without saving first?\";\r\n");
      out.write("//              };\r\n");
      out.write("//    });\r\n");
      out.write("\r\n");
      out.write("}); // End DOM\r\n");
      out.write("\r\n");
      out.write("//Remove row when clicked\r\n");
      out.write("$(\"#deleteRow1\").live('click',function(){\r\n");
      out.write("    $(this).parents('.item-row1').remove();\r\n");
      out.write("    // Hide delete Icon if we only have one row in the list.\r\n");
      out.write("    if ($(\".item-row1\").length < 2) $(\"#deleteRow1\").hide();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" </script>\r\n");
      out.write("\r\n");
      out.write("<Script type=\"text/javascript\">\r\n");
      out.write("function CalculateTotal12(v)\r\n");
      out.write("{\r\n");
      out.write("\t var total12 = 0;\t\r\n");
      out.write("\t try {\r\n");
      out.write("\t\t var $traverse_row = $(v).parents('.item-row');\r\n");
      out.write("\t\t\t$i = $($traverse_row).find('#invcheck');\r\n");
      out.write("\t\t\tvar isChecked = $(v).attr('checked');\r\n");
      out.write("\t\t\tif (isChecked == 'checked'){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t $($i).val($(v).val());\r\n");
      out.write("\t\t\t }else{\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t\t $($i).val('');\r\n");
      out.write("\t\t\t }\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tvar amt15=0;\r\n");
      out.write("\t$('.item-row').each(function(i, row) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar $gstamt1temp = $(row).find('#reamt');\r\n");
      out.write("\t\tvar $gstamt1 = $($gstamt1temp).val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$mycec= $(row).find('#mycec');\r\n");
      out.write("\t \t var isChecked = $($mycec).attr('checked');\r\n");
      out.write("\t \t \r\n");
      out.write("\t \r\n");
      out.write("\t \t \r\n");
      out.write("\t\t if (isChecked == 'checked'){\r\n");
      out.write("\t\t\t amt15=Math.abs(amt15)+ Math.abs($gstamt1);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t \t }\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t document.getElementById(\"dealer_payment_amt\").value=amt15;\r\n");
      out.write("\t document.getElementById(\"net_amount\").value=amt15;\r\n");
      out.write("\t \r\n");
      out.write("\t \r\n");
      out.write("\t }catch (e) {\r\n");
      out.write("\t\t \t\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\t }\r\n");
      out.write("\t \r\n");
      out.write("function qqq(s){\r\n");
      out.write("\t \r\n");
      out.write("\t if (document.getElementById(\"dealer_payment_amt\").value==\"0\") {\r\n");
      out.write("\t\t alert(\"Please chec checbox\");\r\n");
      out.write("\t \t\t      return false;\r\n");
      out.write("\t      \r\n");
      out.write("\t    } else {\r\n");
      out.write("\t      return true;\r\n");
      out.write("\t    }\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body id=\"background\">\r\n");

String lead_no=request.getParameter("lead_no");
String customer_name=request.getParameter("customer_name");
System.out.println("drevt_customer_name:"+customer_name);
String total=request.getParameter("total");
System.out.println("total:"+total);
String invoice_no=request.getParameter("invoice_no");


      out.write("\r\n");
      out.write("<div id=\"container\" class=\"effect mainnav-lg\">\r\n");
      out.write("\t\t<!--NAVBAR-->\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t<!--END NAVBAR-->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"boxed\">\r\n");
      out.write("\t\t\t<!--CONTENT CONTAINER-->\r\n");
      out.write("\t\t\t<div id=\"content-container\">\r\n");
      out.write("\t\t\t\t<!--Page Title-->\r\n");
      out.write("\t\t\t\t<div id=\"page-title\">\r\n");
      out.write("\t\t\t\t\t<h1 class=\"page-header text-overflow\">Customer Payment</h1>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--End page title-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!--Page content-->\r\n");
      out.write("\t\t\t\t<div id=\"page-content\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"panel\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3 class=\"panel-title\"></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t");
      //  s:form
      org.apache.struts2.views.jsp.ui.FormTag _jspx_th_s_005fform_005f0 = (org.apache.struts2.views.jsp.ui.FormTag) _005fjspx_005ftagPool_005fs_005fform_0026_005ftheme_005fonsubmit_005fid_005fclass_005faction.get(org.apache.struts2.views.jsp.ui.FormTag.class);
      _jspx_th_s_005fform_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005fform_005f0.setParent(null);
      // /pages/form/CustomerPayment.jsp(514,2) name = action type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fform_005f0.setAction("insertcustomerpaymentv");
      // /pages/form/CustomerPayment.jsp(514,2) name = onsubmit type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fform_005f0.setOnsubmit("return qqq(this);");
      // /pages/form/CustomerPayment.jsp(514,2) name = theme type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fform_005f0.setTheme("simple");
      // /pages/form/CustomerPayment.jsp(514,2) name = id type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fform_005f0.setId("dealerpayment");
      // /pages/form/CustomerPayment.jsp(514,2) null
      _jspx_th_s_005fform_005f0.setDynamicAttribute(null, "class", "formular");
      int _jspx_eval_s_005fform_005f0 = _jspx_th_s_005fform_005f0.doStartTag();
      if (_jspx_eval_s_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_s_005fform_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.pushBody();
          _jspx_th_s_005fform_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
          _jspx_th_s_005fform_005f0.doInitBody();
        }
        do {
          out.write("\r\n");
          out.write("\t\t\t<div class=\"panel-body\">\r\n");
          out.write("\t\t\t<div class=\"row\" align=\"right\">\r\n");
          out.write("\t\t\t\t\t<div class=\"col-sm-12\">\r\n");
          out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
          out.write("\t\t\t\t\t\t\t<label class=\"control-label\"><input type=\"checkbox\" class=\"form-control\" name=\"withgrid\" value=\"1\" onclick=\"showWithGrid()\" name=\"withgrid\" id=\"withgrid\"/>&nbsp; With Grid</label>\r\n");
          out.write("\t\t\t\t\t\t\t<label class=\"control-label\"><input type=\"checkbox\" class=\"form-control\" name=\"withoutgrid\" value=\"2\"  onclick=\"showwithoutGrid()\" name=\"withoutgrid\" id=\"withoutgrid\"/>&nbsp; Direct</label>\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t  </div>\r\n");
          out.write("\t\t\t\t<div class=\"row\">\r\n");
          out.write("\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
          out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
          out.write("\t\t\t\t\t\t\t<label class=\"control-label\">Date :</label>\r\n");
          out.write("\t\t\t\t\t\t\t<input type=\"hidden\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\tname=\"dpb.voucher_no\" id=\"voucher_no\" size=\"30\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\treadonly=\"true\" tabindex=\"1\">\r\n");
          out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"WithoutGrid\" id=\"WithoutGrid\">\r\n");
          out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"WithGrid\" id=\"WithGrid\">\r\n");
          out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"total_amount\" id=\"total_amount\" value=\"");
          out.print(total);
          out.write("\">\r\n");
          out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"dpb.payment_date\" class=\"form-control\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"payment_date\" size=\"30\" onblur=\"FixShortDate(this);\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"validate[required]\"  cssClass=\"validate[required]\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\ttabindex=\"2\">\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t<div class=\"col-sm-5\" style=\"display: none;\" id=\"customer_name_id\">\r\n");
          out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
          out.write("\t\t\t\t\t\t\t<label class=\"control-label\">Customer&nbsp;Name :</label>\r\n");
          out.write("\t\t\t\t\t\t\t<input type=\"text\"  name=\"dpb.dealer_code\" class=\"form-control\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"dealer_code\" onblur=\"FixShortDate(this);\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"validate[required]\"  cssClass=\"validate[required]\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\ttabindex=\"2\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<input type=\"button\" style=\"margin-left: 428px; margin-top: -32px;\" name=\"Search\" value=\"GO\" class=\"btn btn-primary\" onclick=\"showconfig();\" />\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t<div class=\"col-sm-6\" style=\"display: none;\" id=\"direct_customer_name\">\r\n");
          out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
          out.write("\t\t\t\t\t\t\t<label class=\"control-label\">Customer&nbsp;Name :</label>\r\n");
          out.write("\t\t\t\t\t\t\t<input type=\"text\"  name=\"customer_name\" class=\"form-control\" \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"customer_name\" value=\"");
          out.print(customer_name);
          out.write("\">\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t  </div>\r\n");
          out.write("\t\t\t  \r\n");
          out.write("\t\t\t  <div class=\"row\" style=\"display:none;\" id=\"customer_grid_id\">\r\n");
          out.write("\t\t\t  <table>\r\n");
          out.write("\t\t\t  \t<tr>\r\n");
          out.write("\t\t\t\t\t\t<td colspan=\"9\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<table id=\"itemsTable\" class=\"general-table\">\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<tbody>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</tbody>\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<tbody>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<tr id= \"editdiv\" ><td colspan=\"12\"  style=\"height:1px\" >\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div id=\"documentNoSpan\"></div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td></tr>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</tbody>\r\n");
          out.write("\t\t\t\t\t\t\t\t</table>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t <!-- AddRowDataTable --></td>\r\n");
          out.write("\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t  </table>\r\n");
          out.write("\t\t\t  </div>\r\n");
          out.write("\t\t\t  \r\n");
          out.write("\t\t\t  <div class=\"row\">\r\n");
          out.write("\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
          out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
          out.write("\t\t\t\t\t\t\t<label class=\"control-label\">Paid&nbsp;Amt :</label>\r\n");
          out.write("\t\t\t\t\t\t\t<input type=\"hidden\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\tname=\"dpb.voucher_no\" id=\"voucher_no\" size=\"30\" \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\treadonly=\"true\" tabindex=\"1\">\r\n");
          out.write("\t\t\t\t\t\t\t<input type=\"text\" readonly class=\"form-control\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"dpb.dealer_payment_amt\" id=\"dealer_payment_amt\" \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\tsize=\"30\" maxlength=\"7\" onblur=\"f1();\" \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"validate[required]\" tabindex=\"5\">\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
          out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
          out.write("\t\t\t\t\t\t\t<label class=\"control-label\">Remark :</label>\r\n");
          out.write("\t\t\t\t\t\t\t<input type=\"text\"   name=\"dpb.remark\" class=\"form-control\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"remark\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t  </div>\r\n");
          out.write("\t\t\t  \r\n");
          out.write("\t\t\t  <div class=\"row\">\r\n");
          out.write("\t\t\t  \r\n");
          out.write("\t\t\t  <div class=\"col-sm-6\">\r\n");
          out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
          out.write("\t\t\t\t\t   <p class=\"text-thin mar-btm\">Payment Mode :</p>\r\n");
          out.write("\t\t\t\t\t   <select  tabindex=\"8\" style=\"width:100%;\"\r\n");
          out.write("\t\t\t\t\t\t\tonchange=\"display(this);\" name=\"dpb.paymod\" id=\"paymod\" class=\"validate[required]\"  class=\"selectpicker\" data-live-search=\"true\">\t\t\t\t\t\t\t\t\t\t>\r\n");
          out.write("\t\t\t\t\t\t\t\t<option value=\"\">-------------------SELECT-----------------</option>\r\n");
          out.write("\t\t\t\t\t\t\t\t<option value=\"1\">Cash :</option>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t<option value=\"3\">Cheque :</option>\r\n");
          out.write("\t\t\t\t\t\t\t\t<option value=\"4\">NEFT :</option>\r\n");
          out.write("\t\t\t\t\r\n");
          out.write("\t\t\t\t\t</select>\r\n");
          out.write("\t\t\t\t\t</div>\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t </div>\r\n");
          out.write("\t\t\t \r\n");
          out.write("\t\t\t \t<div class=\"col-sm-6\">\r\n");
          out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
          out.write("\t\t\t\t\t\t\t<label class=\"control-label\">Verified By :</label>\r\n");
          out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"dpb.verifyby\" class=\"form-control\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"verifyby\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\t\t\t  </div>\r\n");
          out.write("\t\t\t  \r\n");
          out.write("\t\t\t\t\t<div class=\"row\">\r\n");
          out.write("\t\t\t   \t\t\t<table >\r\n");
          out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"tab\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<table id=\"itemsTableSpare\"  class=\"table table-striped table-bordered\" cellspacing=\"0\" width=\"100%\">\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tbody id=\"1\" style=\"display: none;\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td  align=\"center\">Net Amount :</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td colspan=\"2\" align=\"center\"><input type=\"text\" class=\"form-control\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tname=\"dpb.net_amount\" id=\"net_amount\" maxlength=8\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tsize=\"15\" readonly=\"readonly\"></td>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tbody>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tbody id=\"8\" style=\"display: none;\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"left\" class=\"style2\">Cash Amount :</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"left\" colspan=\"2\"><input type=\"text\" class=\"form-control\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tname=\"dpb.cash_amt\" id=\"cash_amt\" maxlength=8 id=\"p2\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tsize=\"15\" cssClass=\"validate[required]\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tbody>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tbody id=\"2\" style=\"display: none;\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"style2\" align=\"center\">Bank Name :</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"center\" colspan=\"2\"><input type=\"text\" class=\"form-control\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tname=\"dpb.bankname\" id=\"bankname\" tabindex=\"15\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tmaxlength=30 size=\"15\" class=\"validate[required]\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tbody>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tbody id=\"22\" style=\"display: none;\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"style2\" align=\"center\">Our Bank Name :</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"center\" colspan=\"2\"><input type=\"text\" class=\"form-control\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tname=\"dpb.bankname22\" id=\"bankname22\" tabindex=\"15\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tmaxlength=30 size=\"15\" class=\"validate[required]\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tbody>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tbody id=\"3\" style=\"display: none;\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"style2\" align=\"left\">Cheque No :</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"style2\" align=\"left\">Cheque Amount :</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"style2\" align=\"left\">Cheque Date :</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tbody>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tbody id=\"4\" style=\"display: none;\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"left\"><input type=\"text\" class=\"validate[required]\" class=\"form-control\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tname=\"dpb.cheque_no\" id=\"p4\" maxlength=10 tabindex=\"16\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tsize=\"15\" onkeypress=\"isNumber(event);\"></td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"left\"><input type=\"text\" class=\"form-control\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tname=\"dpb.cheque_amt\" size=\"15\" maxlength=10\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttabindex=\"17\" id=\"p5\" onkeypress=\"isNumber(event);\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"validate[required]\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tmaxlength=\"7\"></td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"left\"><input name=\"dpb.cheque_date\" class=\"form-control\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"\" maxlength=\"20\" id=\"p6\" tabindex=\"18\" class=\"validate[required]\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tonblur=\"FixShortDate(this);return ValidateForm(this);\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tsize=\"10\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tbody>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tbody id=\"5\" style=\"display: none;\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"left\"><input type=\"text\" name=\"dpb.chkno2\" class=\"form-control\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tid=\"p7\" maxlength=10 size=\"15\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tonkeypress=\"isNumber(event);\"></td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"left\"><input type=\"text\" name=\"dpb.amt2\" class=\"form-control\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tsize=\"15\" maxlength=8 id=\"p8\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tonkeypress=\"isNumber(event);\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tcssClass=\"validate[required]\"></td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"left\"><input name=\"dpb.chkdate2\" value=\"\" class=\"form-control\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tmaxlength=\"20\" id=\"p9\" size=\"10\"><a\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\thref=\"javascript:void(0)\"> </a>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tbody>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tbody id=\"6\" style=\"display: none;\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"left\"><input type=\"text\" name=\"dpb.chkno3\" class=\"form-control\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"size=\"15\" onkeypress=\"isNumber(event);\"></td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"left\"><input type=\"text\" name=\"dpb.amt3\" class=\"form-control\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tmaxlength=8 size=\"15\" onkeypress=\"isNumber(event);\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"left\"><input name=\"dpb.chkdate3\" value=\"\" class=\"form-control\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tmaxlength=\"20\" readonly size=\"10\"><a\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\thref=\"javascript:void(0)\"><img\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"PopcalTrigger\" align=\"middle\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tsrc=\"HelloWorld/calbtn.gif\" width=\"34\" height=\"22\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tborder=\"0\" alt=\"\"> </a>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tbody>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tbody id=\"7\" style=\"display: none;\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"style2\" align=\"center\">Transcation&nbsp;Id</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"left\" colspan=\"2\"><input type=\"text\" class=\"form-control\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tname=\"dpb.transcation_id\" id=\"transcation_id\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttabindex=\"19\" onkeypress=\"isNumber(event);\" maxlength=7\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tsize=\"15\" onblur=\"balanceamt();\"></td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tbody>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tbody id=\"7x\" style=\"display: none;\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"style2\" align=\"center\">Supplier Name</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"left\" colspan=\"2\"><input type=\"text\" class=\"form-control\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tname=\"dpb.suppliername\" id=\"suppliername\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttabindex=\"20\" \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tsize=\"15\" ></td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"style2\" align=\"center\">Bank Name</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"left\" colspan=\"2\"><input type=\"text\" class=\"form-control\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tname=\"dpb.supplierbankname\" id=\"supplierbankname\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttabindex=\"20\" \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tsize=\"15\" ></td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"style2\" align=\"center\">Supplier City</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"left\" colspan=\"2\"><input type=\"text\" class=\"form-control\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tname=\"dpb.suppliercity\" id=\"suppliercity\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttabindex=\"20\" \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tsize=\"15\" ></td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tbody>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t</table>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t   \t</table>\r\n");
          out.write("\t\t\t   </div>\r\n");
          out.write("\t\t\t  <div class=\"panel-footer\" >\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-9 col-sm-offset-3\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\"  name=\"lead_no\" value=\"");
          out.print(lead_no);
          out.write("\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\"  name=\"invoice_no\" value=\"");
          out.print(invoice_no);
          out.write("\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-success btn-labeled fa fa-check fa-lg\" style=\"margin-left: 10px\" type=\"submit\" >Submit</button>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-danger btn-labeled fa fa-mail-reply fa-lg\" style=\"margin-left: 10px\" type=\"reset\"  onclick=\"history.go(-1)\">Back</button>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-primary btn-labeled fa fa-repeat fa-lg\" style=\"margin-left: 10px\" type=\"reset\">Reset</button>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t     </div>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_s_005fform_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_s_005fform_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_s_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fs_005fform_0026_005ftheme_005fonsubmit_005fid_005fclass_005faction.reuse(_jspx_th_s_005fform_005f0);
        return;
      }
      _005fjspx_005ftagPool_005fs_005fform_0026_005ftheme_005fonsubmit_005fid_005fclass_005faction.reuse(_jspx_th_s_005fform_005f0);
      out.write("</div></div></div>\r\n");
      out.write("<!--MAIN NAVIGATION-->\r\n");
      out.write("\t\t\t<nav id=\"mainnav-container\">\r\n");
      out.write("\t\t\t\t<div id=\"mainnav\">\r\n");
      out.write("\t\t\t\t\t<!--Shortcut buttons-->\r\n");
      out.write("\t\t\t\t\t<div id=\"mainnav-shortcut\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"list-unstyled\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"col-xs-4\" data-content=\"Additional Sidebar\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a id=\"demo-toggle-aside\" class=\"shortcut-grid\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-magic\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"col-xs-4\" data-content=\"Notification\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a id=\"demo-alert\" class=\"shortcut-grid\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-bullhorn\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"col-xs-4\" data-content=\"Page Alerts\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a id=\"demo-page-alert\" class=\"shortcut-grid\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-bell\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!--End shortcut buttons-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!--Menu-->\r\n");
      out.write("\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/common/leftsidebar.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t\t\t<!--End menu-->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t\t<!--END MAIN NAVIGATION-->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- FOOTER -->\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t<!-- END FOOTER -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- END OF CONTAINER -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- SETTINGS - DEMO PURPOSE ONLY -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/common/settingsForGrid.jsp", out, false);
      out.write("\r\n");
      out.write("\t<!-- END SETTINGS -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
