/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2024-03-11 05:28:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages.form;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class EnquiryForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.2.1.jar", Long.valueOf(1542635950000L));
    _jspx_dependants.put("jar:file:/E:/WORKSPACE/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HSL031220/WEB-INF/lib/struts2-core-2.2.1.jar!/META-INF/struts-tags.tld", Long.valueOf(1279356888000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<link href=\"configure/plugins/bootstrap-datepicker/bootstrap-datepicker.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"Css/jquery-1.10.2.js\" type=\"text/javascript\"></script>\r\n");
      out.write(" <!-- AutoSearch -->\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"Css/styleAS.css\" />\r\n");
      out.write("  <script src=\"js/jquery-migrate-1.2.1.js\" type=\"text/javascript\"></script>\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" media=\"all\" href=\"Css/AutoSearch/styleAS.css\" />\r\n");
      out.write("  <script src=\"jQuery_4_design/AutoSearch/AutoSearchJquerySale.js\" type=\"text/javascript\"></script>\r\n");
      out.write("  <script src=\"js/jquery.validationEngine.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("  <!-- AutoSearch -->\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"js/datevalidation.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"js/rangopopup.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t $(function() {\r\n");
      out.write("\t\t $(\"#source\").autocomplete(\"GoogleSearch/autosearchCity.jsp\");\r\n");
      out.write("\t\t $(\"#destination\").autocomplete(\"GoogleSearch/autosearchCity.jsp\");\r\n");
      out.write("\t\t $(\"#resource_from\").autocomplete(\"GoogleSearch/autosearchResource.jsp\");\r\n");
      out.write("\t\t $(\"#exim\").autocomplete(\"GoogleSearch/autosearchResource2.jsp\");\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t $(\"#name\").autocomplete(\"GoogleSearch/autosearchName.jsp\");\r\n");
      out.write("\t\t $(\"#popupContactcustomer\").hide();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t $(function() {\r\n");
      out.write("\t\t\tvar today = new Date(); \r\n");
      out.write("\t\t\tvar dd = today.getDate(); \r\n");
      out.write("\t\t\tvar mm = today.getMonth()+1;//January is 0! \r\n");
      out.write("\t\t\tvar yyyy = today.getFullYear(); \r\n");
      out.write("\t\t\tif(dd<10){dd='0'+dd} \r\n");
      out.write("\t\t\tif(mm<10){mm='0'+mm} \r\n");
      out.write("\t\t\t$(\"#date\").val(dd+'/'+mm+'/'+yyyy);\r\n");
      out.write("\t\t\t$(\"#date\").focus();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script>\r\n");
      out.write("function checkMobileLength()\r\n");
      out.write("{   \r\n");
      out.write("\t\tvar x=/[a-zA-Z]/g;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\tvar dealer_contact=document.getElementById(\"contact_no\").value;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t if(dealer_contact.length!=0)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif(dealer_contact.match(x))\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\talert(\"Only digit is allowed for mobile number\")\r\n");
      out.write("\t\t\tdocument.getElementById(\"contact_no\").value='';\r\n");
      out.write("\t\t\tdocument.getElementById(\"contact_no\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse if(dealer_contact.length<10||dealer_contact.length>10)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\talert(\"Enter only 10 digits for mobile number\");\r\n");
      out.write("\t\t\tdocument.getElementById(\"contact_no\").value='';\r\n");
      out.write("\t\t\tdocument.getElementById(\"contact_no\").focus();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("    $('form:first *:input[type!=hidden]:first').focus();\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function getDetails(v){\r\n");
      out.write("\t\r\n");
      out.write("\tif (window.XMLHttpRequest) {\r\n");
      out.write("\t\tvar xp1=new XMLHttpRequest();\r\n");
      out.write("\t}\r\n");
      out.write("\telse {\r\n");
      out.write("\t\tvar xp1=new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar name = $(v).val();\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t//var s=document.getElementById(\"model\").value;\r\n");
      out.write("\t//alert(\"1::\"+v);\r\n");
      out.write("\t\r\n");
      out.write("\t xp1.open(\"POST\",\"getCustomerDetails?name=\"+name);\r\n");
      out.write("\r\n");
      out.write("\t// alert(\"2\");\r\n");
      out.write("\t \r\n");
      out.write("\txp1.send();\r\n");
      out.write("\t\r\n");
      out.write("\t//alert(\"3:\");\r\n");
      out.write("\r\n");
      out.write("\txp1.onreadystatechange=function() {\r\n");
      out.write("\r\n");
      out.write("\t\t//alert(\"4\");\r\n");
      out.write("\tif (xp1.readyState==4 && xp1.status==200) {\r\n");
      out.write("\t\r\n");
      out.write("\t\tvar rep=xp1.responseText;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//alert(\"Details:\"+rep);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar detail=rep.split(\"~\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar name=detail[0];\r\n");
      out.write("\t\tvar contact=detail[1];\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\tdocument.getElementById(\"contact_person\").value=name;\r\n");
      out.write("\tdocument.getElementById(\"contact_no\").value=contact;\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\t\r\n");
      out.write("};\r\n");
      out.write("\t\r\n");
      out.write("}\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function openPopupcust() {\r\n");
      out.write("\t\r\n");
      out.write("\tloadPopupcust();\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function disablePopup_cust() {\r\n");
      out.write("//disables popup only if it is enabled\r\n");
      out.write("if (popupStatus_cust == 1) {\r\n");
      out.write("$(\"#backgroundPopup\").fadeOut(\"slow\");\r\n");
      out.write("$(\"#popupContactcustomer\").fadeOut(\"slow\");\r\n");
      out.write("popupStatus_cust = 0;\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function Addinfocust(v) {\r\n");
      out.write("\t//alert(\"144444\");\r\n");
      out.write("\r\n");
      out.write("\tif (window.XMLHttpRequest) {\r\n");
      out.write("\t\tvar xp11 = new XMLHttpRequest();\r\n");
      out.write("\t} else {\r\n");
      out.write("\t\tvar xp11 = new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\tvar temp=0;\r\n");
      out.write("\t\r\n");
      out.write("\t\t//alert(\"1\");\r\n");
      out.write("\r\n");
      out.write("\tvar tab1 = document.getElementById('loc').value;\r\n");
      out.write("\r\n");
      out.write("\t//\talert(\"2\" + tab1);\r\n");
      out.write("\t\r\n");
      out.write("\tif(tab1==\"\")\r\n");
      out.write("\t{\r\n");
      out.write("\t\t temp=false;\r\n");
      out.write("\t\t alert(\"Please Fill Location \");\r\n");
      out.write("\t\t document.getElementById('loc').focus();\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\telse{\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t temp=true;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\tif(temp== true)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\r\n");
      out.write("\txp11.open(\"POST\", \"Add_New_Location?name=\" + tab1 );\r\n");
      out.write("\t\r\n");
      out.write("\txp11.send();\r\n");
      out.write("\t//alert(\"343\");\r\n");
      out.write("\txp11.onreadystatechange = function() {\r\n");
      out.write("\t//\talert(xp11.readyState);\r\n");
      out.write("\t\tif (xp11.readyState == 4 && xp11.status == 200) {\r\n");
      out.write("\t\t\t///$(\"#popupContact\").hide();\r\n");
      out.write("\t\t\t//popupStatus = 0;\r\n");
      out.write("\t\t\t//alert(\"rep\"+xp11.responseText);\r\n");
      out.write("\t\t\tif(xp11.responseText.trim()==\"already\"){\r\n");
      out.write("\t\t\t\talert(\"This Location already exists\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\tdocument.getElementById('loc').value = tab1;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tdisablePopup_cust();\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\treturn temp;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("#popupContactcustomer {\r\n");
      out.write("  position: fixed;\r\n");
      out.write("    top: 50%;\r\n");
      out.write("    left: 40%;\r\n");
      out.write("  transform: translate(-50%, -50%);\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function myFunction() {\r\n");
      out.write("  document.getElementById(\"myBtn\").disabled = true;\r\n");
      out.write(" /*  alert(\"Hiiiii\"); */\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body >\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"container\" class=\"effect mainnav-lg\">\r\n");
      out.write("\t\t<!--NAVBAR-->\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t<!--END NAVBAR-->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"boxed\">\r\n");
      out.write("\t\t\t<!--CONTENT CONTAINER-->\r\n");
      out.write("\t\t\t<div id=\"content-container\">\r\n");
      out.write("\t\t\t\t<!--Page Title-->\r\n");
      out.write("\t\t\t\t<div id=\"page-title\">\r\n");
      out.write("\t\t\t\t\t<h1 class=\"page-header text-overflow\">Enquiry Form</h1>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--End page title-->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!--Breadcrumb-->\r\n");
      out.write("\t\t\t\t<ol class=\"breadcrumb\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Enquiry</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"active\">Enquiry Form</li>\r\n");
      out.write("\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t<!--End breadcrumb-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!--Page content-->\r\n");
      out.write("\t\t\t\t<div id=\"page-content\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"panel\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3 class=\"panel-title\"></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<form action=\"InquiryInsert\" method=\"POST\"  onsubmit=\"myFunction();\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">Date:</label> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\"  id=\"date\" name=\"date\" onblur=\"FixShortDate(this);return ValidateForm(this);\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">Customer Type:</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<select class=\"form-control show-tick \" name=\"type\" id=\"type\" required >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"\">Select</option>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Contracted\">Contracted</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Existing\">Existing</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Non Existing\">Non Existing</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">Customer Name :</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\"  id=\"name\" name=\"name\" onblur=\"getDetails(this);\"  required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">Contact Person :</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\"  id=\"contact_person\" name=\"contact_person\"    required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">Contact No :</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\"  id=\"contact_no\" name=\"contact_no\"   maxlength=\"10\" onblur=\"checkMobileLength();\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">Shipment Type :</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\"  name=\"exim\"  id=\"exim\"  required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">From :</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\"  name=\"source\" id=\"source\"    required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"Button\" class=\"btn btn-primary\" value=\"Location\" onclick=\"openPopupcust();\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">To :</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\"  name=\"destination\"   id=\"destination\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">Resource:</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<select class=\"form-control show-tick \" name=\"resource\" id=\"resource\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\" \">Select</option>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Email\">Email</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"WhatsApp\">WhatsApp</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Phone\">Phone</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  </div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">Resource From :</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\"  name=\"resource_from\"  id=\"resource_from\"  required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">Remark :</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\"  name=\"remark\"  >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <div class=\"panel-footer\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-9 col-sm-offset-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-success btn-labeled fa fa-check fa-lg\" style=\"margin-left: 10px\" type=\"submit\"   id=\"myBtn\">Submit</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-danger btn-labeled fa fa-mail-reply fa-lg\" style=\"margin-left: 10px\" type=\"reset\"  onclick=\"history.go(-1)\">Back</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-primary btn-labeled fa fa-repeat fa-lg\" style=\"margin-left: 10px\" type=\"reset\">Reset</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t     </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t<form action=\"#\" id=\"popupContactcustomer\" style=\"overflow:auto;background-color:#bdd7f9;width:600px;\"  method=\"POST\" style=\"\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<center><h2>Location</h2></center>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div id=\"page-content\" style=\";\">\r\n");
      out.write("\t\t\t\t\t<div class=\"\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("                                            </div>\t\r\n");
      out.write("                                               <div class=\"col-md-6\">\r\n");
      out.write("                                            \t<div class=\"form-group\">\r\n");
      out.write("                                                  <center>  <label for=\"wlastName2\">Location :\r\n");
      out.write("                                                    </label></center>\r\n");
      out.write("                                                    <input type=\"text\" class=\"form-control\"  id=\"loc\"   name=\"loc\"  required> \r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;<button type=\"button\" onclick=\" return Addinfocust(this);\" class=\"btn btn-default w3ls-button\">Submit</button>   \r\n");
      out.write("\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<button type=\"button\"  onclick=\"disablePopup_cust();\" class=\"btn btn-default w3ls-button\">&nbsp;&nbsp;&nbsp;Back&nbsp;&nbsp;&nbsp;</button> \r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("                                       \t\t </div>\r\n");
      out.write("                                       \t\t \r\n");
      out.write("                                         \t\t</div>\r\n");
      out.write("                                         \t\t\r\n");
      out.write("                                         \t\t\r\n");
      out.write("                                         \t\t<div class=\"col-md-6\">\r\n");
      out.write("                                            \t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div id=\"backgroundPopup\"></div></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--End page content-->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--END CONTENT CONTAINER-->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!--MAIN NAVIGATION-->\r\n");
      out.write("\t\t\t<nav id=\"mainnav-container\">\r\n");
      out.write("\t\t\t\t<div id=\"mainnav\">\r\n");
      out.write("\t\t\t\t\t<!--Shortcut buttons-->\r\n");
      out.write("\t\t\t\t\t<div id=\"mainnav-shortcut\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"list-unstyled\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"col-xs-4\" data-content=\"Additional Sidebar\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a id=\"demo-toggle-aside\" class=\"shortcut-grid\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-magic\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"col-xs-4\" data-content=\"Notification\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a id=\"demo-alert\" class=\"shortcut-grid\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-bullhorn\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"col-xs-4\" data-content=\"Page Alerts\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a id=\"demo-page-alert\" class=\"shortcut-grid\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-bell\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!--End shortcut buttons-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!--Menu-->\r\n");
      out.write("\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/common/leftsidebar.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t\t\t<!--End menu-->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t\t<!--END MAIN NAVIGATION-->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- FOOTER -->\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t<!-- END FOOTER -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- END OF CONTAINER -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- SETTINGS - DEMO PURPOSE ONLY -->\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/common/settingsForGrid.jsp", out, false);
      out.write("\r\n");
      out.write("\t<!-- END SETTINGS -->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
