/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2024-03-08 05:59:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages.form;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class OrderLrFormView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.2.1.jar", Long.valueOf(1542635950000L));
    _jspx_dependants.put("jar:file:/E:/WORKSPACE/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HSL031220/WEB-INF/lib/struts2-core-2.2.1.jar!/META-INF/struts-tags.tld", Long.valueOf(1279356888000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fpush_0026_005fvalue;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fiterator_0026_005fvalue;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fs_005fpush_0026_005fvalue = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fiterator_0026_005fvalue = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fs_005fpush_0026_005fvalue.release();
    _005fjspx_005ftagPool_005fs_005fiterator_0026_005fvalue.release();
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<link href=\"configure/plugins/bootstrap-datepicker/bootstrap-datepicker.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"Css/jquery-1.10.2.js\" type=\"text/javascript\"></script>\r\n");
      out.write(" <!-- AutoSearch -->\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"Css/styleAS.css\" />\r\n");
      out.write("  <script src=\"js/jquery-migrate-1.2.1.js\" type=\"text/javascript\"></script>\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" media=\"all\" href=\"Css/AutoSearch/styleAS.css\" />\r\n");
      out.write("  <script src=\"jQuery_4_design/AutoSearch/AutoSearchJquerySale.js\" type=\"text/javascript\"></script>\r\n");
      out.write("  <script src=\"js/jquery.validationEngine.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("  <!-- AutoSearch -->\r\n");
      out.write("\t\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t <script>\r\n");
      out.write("\t $(function() {\r\n");
      out.write("\t\t $(\"#driver_name\").autocomplete(\"GoogleSearch/autosearchDriver.jsp\");\r\n");
      out.write("\t\t $(\"#vehicle_no\").autocomplete(\"GoogleSearch/autosearchVehicle.jsp\");\r\n");
      out.write("\t\t $(\"#source\").autocomplete(\"GoogleSearch/autosearchCity.jsp\");\r\n");
      out.write("\t\t $(\"#destination\").autocomplete(\"GoogleSearch/autosearchCity.jsp\");\r\n");
      out.write("\t\t $(\"#next_destination\").autocomplete(\"GoogleSearch/autosearchCity.jsp\");\r\n");
      out.write("\t\t $(\"#customer_name\").autocomplete(\"GoogleSearch/autosearchCustomer.jsp\");\r\n");
      out.write("\t\t $(\"#description\").autocomplete(\"GoogleSearch/spareautosearch.jsp\");\r\n");
      out.write("\t\t $(\"#transporter_name\").autocomplete(\"GoogleSearch/transporterautosearch.jsp\");\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t $(\"#111\").hide();\r\n");
      out.write("\t\t\t$(\"#222\").hide();\r\n");
      out.write("\t\t\t$(\"#333\").hide();\r\n");
      out.write("\t\t\t$(\"#444\").hide();\r\n");
      out.write("\t\t\t$(\"#555\").hide();\r\n");
      out.write("\t\t\t$(\"#666\").hide();\r\n");
      out.write("\t});\r\n");
      out.write("\t \r\n");
      out.write("\t \r\n");
      out.write("\tfunction getAddress(v){\r\n");
      out.write("\t\t \r\n");
      out.write("\t\tif (window.XMLHttpRequest) {\r\n");
      out.write("\t\t\tvar xp11 = new XMLHttpRequest();\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tvar xp11 = new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t //alert('Inside');\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t \r\n");
      out.write("\t\t var cname = v.value;\r\n");
      out.write("\t\t var tname = document.getElementById('transporter_name').value;\r\n");
      out.write("\t\t //alert('cust nm'+cname);\r\n");
      out.write("\t\t //alert('trans nm'+tname);\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t \r\n");
      out.write("\t\t var cust = cname.split(\"-\");\r\n");
      out.write("\t\t var trans = tname.split(\"-\");\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t //alert(\"cust code: \"+cust[1]);\r\n");
      out.write("\t\t //alert(\"trans code: \"+trans[1]);\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t \r\n");
      out.write("\t\t \r\n");
      out.write("\t\t \r\n");
      out.write("\t\t \r\n");
      out.write("\t\t xp11.open(\"POST\", \"Get_Address?transporter_code=\"\r\n");
      out.write("\t\t\t\t\t+ trans[1] + \"&customer_code=\"\r\n");
      out.write("\t\t\t\t\t+ cust[1]);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\txp11.send();\r\n");
      out.write("\t\t\t//alert(\"343\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//alert(\"343\");\r\n");
      out.write("\t\t\t xp11.onreadystatechange = function() {\r\n");
      out.write("\t\t\t if (xp11.readyState == 4 && xp11.status == 200) {\r\n");
      out.write("\t\t\t\t //alert('333');\r\n");
      out.write("\t\t\t\t var rep = xp11.responseText;\r\n");
      out.write("\t\t\t\t parts = rep.split(\"^\");\r\n");
      out.write("\t\t\t\t //alert('444');\r\n");
      out.write("\t\t\t\t var tadd = parts[0];\r\n");
      out.write("\t\t\t\t var cadd = parts[1];\r\n");
      out.write("\t\t\t\t //alert('555');\r\n");
      out.write("\t\t\t\t document.getElementById('transporter_addr').value = tadd;\r\n");
      out.write("\t\t\t\t document.getElementById('customer_addr').value = cadd;\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t  };\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t }\r\n");
      out.write("\t \r\n");
      out.write("\t \r\n");
      out.write("\t \r\n");
      out.write("\t function getRNA(v)\r\n");
      out.write("\t {\r\n");
      out.write("\t\t var $traverse_row = $(v).parents('.item-row');\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//\talert(\">>>\");\r\n");
      out.write("\t\t\t\t$hoardinglocationx1 = $($traverse_row).find('#rate');\r\n");
      out.write("\t\t\t\t//alert(\">>>\");\r\n");
      out.write("\t\t\t\t$hoardinglocationx = $($traverse_row).find('#weight');\r\n");
      out.write("\t\t\t//\talert(\">>>\");\r\n");
      out.write("\t\t\t\t/* $hoardinglocation3 = $($traverse_row).find('#amount'); */\r\n");
      out.write("\t\t\t\t$('.item-row').each(function(i,row){\r\n");
      out.write("\t\t\t\tvar weight = $($hoardinglocationx).val();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar rate = $($hoardinglocationx1).val();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t/* var amount = $($hoardinglocation3).val();  */\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(weight!=\"\" && rate!=\"\" ){\r\n");
      out.write("\t\t\t\t\tamt= rate * weight;\r\n");
      out.write("\t\t\t\t\t$hoardinglocation = $($traverse_row).find('#amount');\r\n");
      out.write("\t\t\t\t\t//alert(amt);\r\n");
      out.write("\t\t\t\t\t$($hoardinglocation).val(amt);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t\t\t});\t\r\n");
      out.write("    \t\t //alert(\"1234567\");\r\n");
      out.write("    \t\t /* var $vid = $(row).find('#weight');\r\n");
      out.write("    \t\t var $vid1 = $(row).find('#rate');\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t var $vid2 = $vid * $vid1;\r\n");
      out.write("    \t\t \r\n");
      out.write("    \t\t alert($vid2);\r\n");
      out.write("    \t\t \r\n");
      out.write("    \t\t $(row).find('#amount').value = $vid2; */\r\n");
      out.write("    \t\t \r\n");
      out.write("    \t \r\n");
      out.write("    \t \r\n");
      out.write("\t\t \r\n");
      out.write("\t\t /* var amount = weight * rate;\r\n");
      out.write("\t\t alert(\"amount : \"+amount);\r\n");
      out.write("\t\t document.getElementById(\"amount\").value = amount; */\r\n");
      out.write("\t }\r\n");
      out.write("\t \r\n");
      out.write("\t function getTotal(v)\r\n");
      out.write("\t {\r\n");
      out.write("\t\t// alert('getTotal()');\r\n");
      out.write("\t\t /* var $traverse_row = $(v).parents('.item-row');\r\n");
      out.write("\t\t var tot_amt = 0; */\r\n");
      out.write("\t\t/*  $hoardinglocationx = $($traverse_row).find('#amount'); */\r\n");
      out.write("\t\t /* $hoardinglocationx = $($traverse_row).find('#amount');\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t $('.item-row').each(function(i,row){\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t var amount = $($hoardinglocationx).val();\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t tot_amt = Math.abs(tot_amt) + Math.abs(amount);\r\n");
      out.write("\t\t\t  */\r\n");
      out.write("\t\t\t /* $hoardinglocation = $($traverse_row).find('#total_amount'); */\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t /* });\t\r\n");
      out.write("\t\t//alert(tot_amt);\r\n");
      out.write("\t\tdocument.getElementById(\"total_amount\").value = tot_amt; */\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar amount=0;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t var $traverse_row = $(v).parents('.item-row');\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\tvar $hoardinglocation1 = $($traverse_row).find('#amount');\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\tvar tax2=$($hoardinglocation1).val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('.item-row').each(function(i, row) {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar $totamttemp = $(row).find('#amount');\r\n");
      out.write("\t\t\t\tvar totamt = $($totamttemp).val();\r\n");
      out.write("\t\t\t\tamount=Math.abs(amount)+ Math.abs(totamt);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t//alert(\"Total:\"+amount);\r\n");
      out.write("\t\t\t//alert(amount);\r\n");
      out.write("\t\t\tdocument.getElementById(\"total_amount\").value=amount;\r\n");
      out.write("\t\t\r\n");
      out.write("\t }\r\n");
      out.write("\t \r\n");
      out.write("\t function getBalance(v)\r\n");
      out.write("\t {\r\n");
      out.write("\t\t var advance = v.value;\r\n");
      out.write("\t\t var total = document.getElementById('total_amount').value;\r\n");
      out.write("\t\t var balance = Math.abs(total) - Math.abs(advance);\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t// alert(balance);\r\n");
      out.write("\t\t document.getElementById(\"balance\").value = balance;\r\n");
      out.write("\t }\r\n");
      out.write("\t \r\n");
      out.write("\t function showmyd1(v){\r\n");
      out.write("\t\t var isChecked = $(v).attr('checked');\r\n");
      out.write("\t\t var myv=$(v).val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tif(myv==\"myd1\"){\r\n");
      out.write("\t\t\tif(isChecked==\"checked\"){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#111\").show(1000);\r\n");
      out.write("\t\t\t\t$(\"#222\").show(1000);\r\n");
      out.write("\t\t\t\t$(\"#333\").show(1000);\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$(\"#111\").hide();\r\n");
      out.write("\t\t\t\t$(\"#222\").hide();\r\n");
      out.write("\t\t\t\t$(\"#333\").hide();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(myv==\"myd2\"){\r\n");
      out.write("\t\t\tif(isChecked==\"checked\"){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"#444\").show(1000);\r\n");
      out.write("\t\t\t\t\t$(\"#555\").show(1000);\r\n");
      out.write("\t\t\t\t\t$(\"#666\").show(1000);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$(\"#444\").hide();\r\n");
      out.write("\t\t\t\t\t$(\"#555\").hide();\r\n");
      out.write("\t\t\t\t\t$(\"#666\").hide(1000);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t \r\n");
      out.write("\t </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"container\" class=\"effect mainnav-lg\">\r\n");
      out.write("\t\t<!--NAVBAR-->\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t<!--END NAVBAR-->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"boxed\">\r\n");
      out.write("\t\t\t<!--CONTENT CONTAINER-->\r\n");
      out.write("\t\t\t<div id=\"content-container\">\r\n");
      out.write("\t\t\t\t<!--Page Title-->\r\n");
      out.write("\t\t\t\t<div id=\"page-title\">\r\n");
      out.write("\t\t\t\t\t<h1 class=\"page-header text-overflow\">LR Form View</h1>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--End page title-->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!--Breadcrumb-->\r\n");
      out.write("\t\t\t\t<ol class=\"breadcrumb\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">LR</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"active\">LR Form View</li>\r\n");
      out.write("\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t<!--End breadcrumb-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!--Page content-->\r\n");
      out.write("\t\t\t\t<div id=\"page-content\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"panel\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3 class=\"panel-title\"></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <form action=\"insert_lr_action\" method=\"POST\"> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      if (_jspx_meth_s_005fpush_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--End page content-->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--END CONTENT CONTAINER-->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!--MAIN NAVIGATION-->\r\n");
      out.write("\t\t\t<nav id=\"mainnav-container\">\r\n");
      out.write("\t\t\t\t<div id=\"mainnav\">\r\n");
      out.write("\t\t\t\t\t<!--Shortcut buttons-->\r\n");
      out.write("\t\t\t\t\t<div id=\"mainnav-shortcut\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"list-unstyled\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"col-xs-4\" data-content=\"Additional Sidebar\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a id=\"demo-toggle-aside\" class=\"shortcut-grid\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-magic\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"col-xs-4\" data-content=\"Notification\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a id=\"demo-alert\" class=\"shortcut-grid\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-bullhorn\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"col-xs-4\" data-content=\"Page Alerts\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a id=\"demo-page-alert\" class=\"shortcut-grid\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-bell\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!--End shortcut buttons-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!--Menu-->\r\n");
      out.write("\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/common/leftsidebar.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t\t\t<!--End menu-->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t\t<!--END MAIN NAVIGATION-->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- FOOTER -->\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t<!-- END FOOTER -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- END OF CONTAINER -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- SETTINGS - DEMO PURPOSE ONLY -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/common/settingsForGrid.jsp", out, false);
      out.write("\r\n");
      out.write("\t<!-- END SETTINGS -->\r\n");
      out.write("\t<script src=\"configure/plugins/bootstrap-datepicker/bootstrap-datepicker.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_s_005fpush_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:push
    org.apache.struts2.views.jsp.PushTag _jspx_th_s_005fpush_005f0 = (org.apache.struts2.views.jsp.PushTag) _005fjspx_005ftagPool_005fs_005fpush_0026_005fvalue.get(org.apache.struts2.views.jsp.PushTag.class);
    _jspx_th_s_005fpush_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fpush_005f0.setParent(null);
    // /pages/form/OrderLrFormView.jsp(278,8) name = value type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fpush_005f0.setValue("tripModel1");
    int _jspx_eval_s_005fpush_005f0 = _jspx_th_s_005fpush_005f0.doStartTag();
    if (_jspx_eval_s_005fpush_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_s_005fpush_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_s_005fpush_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_s_005fpush_005f0.doInitBody();
      }
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">Date:</label>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\"  style=\"line-height: 15px;\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" name=\"date\" id=\"date\" class=\"form-control\" readonly>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">LR Number:</label>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\"   value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lr_number}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" name=\"lr_number\" id=\"lr_number\" class=\"form-control\" readonly>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  </div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t      <div class=\"row\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">From:</label>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"trip_id\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${trip_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"updown_id\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${updown_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"updown\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${updown}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${source}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" name=\"source\" id=\"source\"  onkeyup=\"this.value=this.value.toUpperCase()\" class=\"form-control\" readonly>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">Destination:</label>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${destination}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" name=\"destination\" id=\"destination\"  onkeyup=\"this.value=this.value.toUpperCase()\" class=\"form-control\" readonly>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  </div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \r\n");
        out.write("\t\t\t\t\t\t\t\t\t  <div class=\"row\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">Transporter Name:</label>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${transporter_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write('-');
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${transporter_code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" name=\"transporter_name\" id=\"transporter_name\"  onkeyup=\"this.value=this.value.toUpperCase()\" class=\"form-control\" readonly>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">Customer Name:</label>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${customer_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write('-');
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${customer_code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\"  name=\"customer_name\" id=\"customer_name\"  onkeyup=\"this.value=this.value.toUpperCase()\" class=\"form-control\" readonly>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  </div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \r\n");
        out.write("\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" class=\"form-control\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${transporter_addr}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" name=\"transporter_addr\" id=\"transporter_addr\"  onkeyup=\"this.value=this.value.toUpperCase()\" class=\"form-control\" readonly>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" class=\"form-control\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${customer_addr}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" name=\"customer_addr\" id=\"customer_addr\"  onkeyup=\"this.value=this.value.toUpperCase()\" class=\"form-control\" readonly>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \r\n");
        out.write("\t\t\t\t\t\t\t\t\t  <div class=\"row\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \t\t<div class=\"col-sm-6\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">Vehicle No:</label>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\"  name=\"vehicle_no\" id=\"vehicle_no\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vehicle_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\"  onkeyup=\"this.value=this.value.toUpperCase()\" class=\"form-control\" readonly>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">Driver Name:</label>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\"  name=\"driver_name\"  id=\"driver_name\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${driver_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write('-');
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${driver_code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\"  onkeyup=\"this.value=this.value.toUpperCase()\" class=\"form-control\" readonly>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  </div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \r\n");
        out.write("\t\t\t\t\t\t\t\t\t  <div class=\"row\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" class=\"form-control\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${commission}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" name=\"commission\" id=\"commission\"  class=\"form-control\" readonly>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" class=\"form-control\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${order_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" name=\"order_id\" id=\"order_id\"  readonly>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t <div class=\"col-sm-6\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">Driver Contact </label>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${driver_mobile}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" name=\"driver_mobile\" id=\"driver_mobile\"   readonly>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">Volume:</label>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${volume}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" name=\"volume\" id=\"volume\"  readonly>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  </div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \r\n");
        out.write("\t\t\t\t\t\t\t\t\t  <div class=\"row\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">Insurance Type:</label>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<select class=\"form-control show-tick \" name=\"insurance\" id=\"insurance\" readonly>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${insurance}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write(' ');
        out.write('"');
        out.write('>');
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${insurance}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</option>\r\n");
        out.write("\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  </div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">Mode Of Booking :</label>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<select class=\"form-control show-tick \" name=\"booking\" id=\"booking\" readonly>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${booking}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write('"');
        out.write('>');
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${booking}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</option>\r\n");
        out.write("\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  </div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  </div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \r\n");
        out.write("\t\t\t\t\t\t\t\t\t  <div class=\"row\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">Value Rupees:</label>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${val_rupees}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\"  name=\"val_rupees\" id=\"val_rupees\"  readonly>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">Mode Of Freight :</label>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<select class=\"form-control show-tick \" name=\"freight\" id=\"freight\" readonly>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freight}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write('"');
        out.write('>');
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${freight}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</option>\r\n");
        out.write("\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  </div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  </div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \r\n");
        out.write("\t\t\t\t\t\t\t\t\t  <div class=\"row\">\r\n");
        out.write("                                         <div class=\"col-md-6\">\r\n");
        out.write("                                                <div class=\"form-group\">\r\n");
        out.write("                                        \t\t \t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"myd2\"  id=\"myd2\" onclick=\"showmyd1(this)\" value=\"myd2\"  >&nbsp;&nbsp;&nbsp;<b>Shipment Details</b>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type=\"checkbox\" name=\"myd1\"  id=\"myd1\" onclick=\"showmyd1(this)\" value=\"myd1\"  >&nbsp;&nbsp;&nbsp;<b>Loading Details</b>\r\n");
        out.write("                                         \t\t</div>\r\n");
        out.write("                                         \t</div>\r\n");
        out.write("                                         </div>\r\n");
        out.write("                                         \r\n");
        out.write("                                         \r\n");
        out.write("                                  \t  \r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \r\n");
        out.write("\t\t\t\t\t\t\t\t\t  <div class=\"row\"  id=\"444\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \t\t<div class=\"col-sm-6\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">Ship To Party :</label>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${shipname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" name=\"shipname\" name=\"shipname\" readonly>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">Shipping Address</label>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${shipadd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" name=\"shipadd\" id=\"shipadd\"  readonly>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \r\n");
        out.write("\t\t\t\t\t\t\t\t\t  </div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \r\n");
        out.write("\t\t\t\t\t\t\t\t\t   <div class=\"row\"  id=\"555\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">Ship State</label>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${shipstate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\"  name=\"shipstate\" id=\"shipstate\"  readonly>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \r\n");
        out.write("\t\t\t\t\t\t\t\t\t  <div class=\"col-sm-6\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">Ship GSTIN NO :</label>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${shipgstn}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\"  name=\"shipgstn\" id=\"shipgstn\" readonly >\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \r\n");
        out.write("\t\t\t\t\t\t\t\t\t   </div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t   \r\n");
        out.write("\t\t\t\t\t\t\t\t\t   \r\n");
        out.write("\t\t\t\t\t\t\t\t\t   <div class=\"row\" id=\"666\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">Contact Person:</label>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dest_contact_person}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" name=\"dest_contact_person\" id=\"dest_contact_person\"   readonly>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">Contact Number:</label>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dest_contact_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" name=\"dest_contact_no\" id=\"dest_contact_no\" onblur=\"checkMobileLength2(this);\"  readonly>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  </div>\r\n");
        out.write("                                         \r\n");
        out.write("\t\t\t\t\t\t\t\t\t  <div class=\"row\"  id=\"111\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \t\t<div class=\"col-sm-6\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">Load Party :</label>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loadname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" name=\"loadname\" name=\"loadname\" readonly>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">Loading Address</label>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loadadd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" name=\"loadadd\" id=\"loadadd\" readonly >\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \r\n");
        out.write("\t\t\t\t\t\t\t\t\t  </div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \r\n");
        out.write("\t\t\t\t\t\t\t\t\t   <div class=\"row\"  id=\"222\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">Loading State</label>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loadstate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\"  name=\"loadstate\" id=\"loadstate\"  readonly>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \r\n");
        out.write("\t\t\t\t\t\t\t\t\t  <div class=\"col-sm-6\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">Loading GSTIN NO :</label>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loadgstn}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" name=\"loadgstn\" id=\"loadgstn\"  readonly>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \r\n");
        out.write("\t\t\t\t\t\t\t\t\t   </div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t   \r\n");
        out.write("\t\t\t\t\t\t\t\t\t   \r\n");
        out.write("\t\t\t\t\t\t\t\t\t   <div class=\"row\"  id=\"333\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">Contact Person</label>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${load_contact_person}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\"  name=\"load_contact_person\" id=\"load_contact_person\"  readonly>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \r\n");
        out.write("\t\t\t\t\t\t\t\t\t  <div class=\"col-sm-6\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">Contact Number:</label>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${load_contact_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" name=\"load_contact_no\" id=\"load_contact_no\" readonly >\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \r\n");
        out.write("\t\t\t\t\t\t\t\t\t   </div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \r\n");
        out.write("\t\t\t\t\t\t\t\t\t  <div id=\"product\" style=\"width:100%\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<table id=\"itemsTable\" class=\"table table-striped table-bordered\" cellspacing=\"0\" width=\"70%\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th style=\"\">Delete</th>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th id=\"VLsparename\"><label>NO Of Packages</label> </th>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th id=\"VLsparename\"><label>Type Of Packing</label> </th>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th id=\"VLsparename\"><label>Description</label> </th>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th id=\"VLsparename\"><label>Vehicle Type</label> </th>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th id=\"VLsparename\"><label>Source</label> </th>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th id=\"VLsparename\"><label>Destination</label> </th>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th id=\"VLsparename\"><label>Weight</label> </th>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th id=\"VLsparename\"><label>Rate</label></th>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t<th id=\"VLsparename\"><label>Amount</label></th>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t</tr>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t ");
        if (_jspx_meth_s_005fiterator_005f0(_jspx_th_s_005fpush_005f0, _jspx_page_context))
          return true;
        out.write(" \r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t</table>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t<table id=\"TaNAB\" class=\"table table-striped table-bordered\" cellspacing=\"0\" width=\"70%\">\r\n");
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Total Amount</td>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"total_amount\" class=\"form-control\"\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tid=\"total_amount\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${total_amount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\"\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttabindex=\"12\"\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: 120px;\" readonly/></td>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Total Weight</td>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"advance\" class=\"form-control\"\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tid=\"advance\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${advance}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\"\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttabindex=\"12\" \r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: 120px;\" readonly/></td>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</table>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t \r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"panel-footer\" >\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-9 col-sm-offset-3\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t<!-- <button class=\"btn btn-success btn-labeled fa fa-check fa-lg\" style=\"margin-left: 10px\" type=\"submit\" >Submit</button> -->\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-danger btn-labeled fa fa-mail-reply fa-lg\" style=\"margin-left: 10px\" type=\"reset\"  onclick=\"history.go(-1)\">Back</button>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t<!-- <button class=\"btn btn-primary btn-labeled fa fa-repeat fa-lg\" style=\"margin-left: 10px\" type=\"reset\">Reset</button> -->\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t     </div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_s_005fpush_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_s_005fpush_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_s_005fpush_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fpush_0026_005fvalue.reuse(_jspx_th_s_005fpush_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fpush_0026_005fvalue.reuse(_jspx_th_s_005fpush_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005fiterator_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fpush_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:iterator
    org.apache.struts2.views.jsp.IteratorTag _jspx_th_s_005fiterator_005f0 = (org.apache.struts2.views.jsp.IteratorTag) _005fjspx_005ftagPool_005fs_005fiterator_0026_005fvalue.get(org.apache.struts2.views.jsp.IteratorTag.class);
    _jspx_th_s_005fiterator_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fiterator_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fpush_005f0);
    // /pages/form/OrderLrFormView.jsp(618,20) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fiterator_005f0.setValue("tripDetails");
    int _jspx_eval_s_005fiterator_005f0 = _jspx_th_s_005fiterator_005f0.doStartTag();
    if (_jspx_eval_s_005fiterator_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_s_005fiterator_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_s_005fiterator_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_s_005fiterator_005f0.doInitBody();
      }
      do {
        out.write(" \r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr class=\"item-row\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td style=\"width:1px;\"></td>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><input type=\"text\" value=\"");
        if (_jspx_meth_s_005fproperty_005f0(_jspx_th_s_005fiterator_005f0, _jspx_page_context))
          return true;
        out.write("\" name=\"aa\" class=\"form-control\" style=\"width: 80px;\"  id=\"aa\" readonly/></td>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><input type=\"text\"  value=\"");
        if (_jspx_meth_s_005fproperty_005f1(_jspx_th_s_005fiterator_005f0, _jspx_page_context))
          return true;
        out.write("\" name=\"bb\" class=\"form-control\" style=\"width: 80px;\"  id=\"bb\" readonly/></td>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><input type=\"text\"  value=\"");
        if (_jspx_meth_s_005fproperty_005f2(_jspx_th_s_005fiterator_005f0, _jspx_page_context))
          return true;
        out.write("\" name=\"cc\" class=\"form-control\" style=\"width: 250px;\" id=\"cc\"  readonly/></td>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><input type=\"text\" value=\"");
        if (_jspx_meth_s_005fproperty_005f3(_jspx_th_s_005fiterator_005f0, _jspx_page_context))
          return true;
        out.write("\" name=\"dd\" class=\"form-control\" id=\"dd\"  style=\"width: 80px;\" readonly/> </td>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><input type=\"text\" value=\"");
        if (_jspx_meth_s_005fproperty_005f4(_jspx_th_s_005fiterator_005f0, _jspx_page_context))
          return true;
        out.write("\" name=\"ee\" class=\"form-control\" id=\"ee\"   style=\"width: 100px;\"  readonly/> </td>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><input type=\"text\" value=\"");
        if (_jspx_meth_s_005fproperty_005f5(_jspx_th_s_005fiterator_005f0, _jspx_page_context))
          return true;
        out.write("\" name=\"ff\" class=\"form-control\" id=\"ff\"  style=\"width: 100px;\"  readonly/> </td>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><input type=\"text\" value=\"");
        if (_jspx_meth_s_005fproperty_005f6(_jspx_th_s_005fiterator_005f0, _jspx_page_context))
          return true;
        out.write("\" name=\"gg\" onblur=\"getTotal(this);\" class=\"form-control\" id=\"gg\"  style=\"width: 80px;\"  readonly/> </td>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><input type=\"text\" value=\"");
        if (_jspx_meth_s_005fproperty_005f7(_jspx_th_s_005fiterator_005f0, _jspx_page_context))
          return true;
        out.write("\" name=\"hh\" onblur=\"getAmount(this);\" class=\"form-control\" id=\"hh\"  style=\"width: 80px;\"  readonly/> </td>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><input type=\"text\" value=\"");
        if (_jspx_meth_s_005fproperty_005f8(_jspx_th_s_005fiterator_005f0, _jspx_page_context))
          return true;
        out.write("\" name=\"ii\" onblur=\"getTotal1(this);\" class=\"form-control\" id=\"ii\"  style=\"width: 80px;\"  readonly/> </td>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t</tr>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_s_005fiterator_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_s_005fiterator_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_s_005fiterator_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fiterator_0026_005fvalue.reuse(_jspx_th_s_005fiterator_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fiterator_0026_005fvalue.reuse(_jspx_th_s_005fiterator_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fiterator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f0 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fiterator_005f0);
    // /pages/form/OrderLrFormView.jsp(624,47) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f0.setValue("aa1");
    int _jspx_eval_s_005fproperty_005f0 = _jspx_th_s_005fproperty_005f0.doStartTag();
    if (_jspx_th_s_005fproperty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fiterator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f1 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f1.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fiterator_005f0);
    // /pages/form/OrderLrFormView.jsp(626,49) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f1.setValue("bb1");
    int _jspx_eval_s_005fproperty_005f1 = _jspx_th_s_005fproperty_005f1.doStartTag();
    if (_jspx_th_s_005fproperty_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f1);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fiterator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f2 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f2.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fiterator_005f0);
    // /pages/form/OrderLrFormView.jsp(628,49) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f2.setValue("cc1");
    int _jspx_eval_s_005fproperty_005f2 = _jspx_th_s_005fproperty_005f2.doStartTag();
    if (_jspx_th_s_005fproperty_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f2);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fiterator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f3 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f3.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fiterator_005f0);
    // /pages/form/OrderLrFormView.jsp(630,48) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f3.setValue("dd1");
    int _jspx_eval_s_005fproperty_005f3 = _jspx_th_s_005fproperty_005f3.doStartTag();
    if (_jspx_th_s_005fproperty_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f3);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fiterator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f4 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f4.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fiterator_005f0);
    // /pages/form/OrderLrFormView.jsp(632,48) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f4.setValue("ee1");
    int _jspx_eval_s_005fproperty_005f4 = _jspx_th_s_005fproperty_005f4.doStartTag();
    if (_jspx_th_s_005fproperty_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f4);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fiterator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f5 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f5.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fiterator_005f0);
    // /pages/form/OrderLrFormView.jsp(634,48) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f5.setValue("ff1");
    int _jspx_eval_s_005fproperty_005f5 = _jspx_th_s_005fproperty_005f5.doStartTag();
    if (_jspx_th_s_005fproperty_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f5);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fiterator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f6 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f6.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fiterator_005f0);
    // /pages/form/OrderLrFormView.jsp(636,48) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f6.setValue("gg1");
    int _jspx_eval_s_005fproperty_005f6 = _jspx_th_s_005fproperty_005f6.doStartTag();
    if (_jspx_th_s_005fproperty_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f6);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f6);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fiterator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f7 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f7.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fiterator_005f0);
    // /pages/form/OrderLrFormView.jsp(638,48) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f7.setValue("hh1");
    int _jspx_eval_s_005fproperty_005f7 = _jspx_th_s_005fproperty_005f7.doStartTag();
    if (_jspx_th_s_005fproperty_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f7);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f7);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f8(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fiterator_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f8 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f8.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f8.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fiterator_005f0);
    // /pages/form/OrderLrFormView.jsp(640,48) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f8.setValue("ii1");
    int _jspx_eval_s_005fproperty_005f8 = _jspx_th_s_005fproperty_005f8.doStartTag();
    if (_jspx_th_s_005fproperty_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f8);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f8);
    return false;
  }
}
