/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2024-03-12 13:23:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages.form;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.text.SimpleDateFormat;
import java.util.Date;
import com.DB.DBConnection;
import java.sql.*;

public final class rootGraph4_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1542635938000L));
    _jspx_dependants.put("jar:file:/E:/WORKSPACE/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HSL031220/WEB-INF/lib/struts2-dojo-plugin-2.1.2.jar!/META-INF/struts-dojo-tags.tld", Long.valueOf(1209663602000L));
    _jspx_dependants.put("/WEB-INF/lib/struts2-dojo-plugin-2.1.2.jar", Long.valueOf(1542635948000L));
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.2.1.jar", Long.valueOf(1542635950000L));
    _jspx_dependants.put("jar:file:/E:/WORKSPACE/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HSL031220/WEB-INF/lib/struts2-core-2.2.1.jar!/META-INF/struts-tags.tld", Long.valueOf(1279356888000L));
    _jspx_dependants.put("jar:file:/E:/WORKSPACE/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HSL031220/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098691290000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.DB.DBConnection");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<link href=\"configure/plugins/bootstrap-datepicker/bootstrap-datepicker.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"Css/jquery-1.10.2.js\" type=\"text/javascript\"></script>\r\n");
      out.write(" <!-- AutoSearch -->\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"Css/styleAS.css\" />\r\n");
      out.write("  <script src=\"js/jquery-migrate-1.2.1.js\" type=\"text/javascript\"></script>\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" media=\"all\" href=\"Css/AutoSearch/styleAS.css\" />\r\n");
      out.write("  <link href=\"configure/css/gcss.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"configure/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"configure/css/nifty.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"configure/plugins/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"configure/plugins/animate-css/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"configure/plugins/morris-js/morris.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"configure/plugins/switchery/switchery.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"configure/plugins/bootstrap-select/bootstrap-select.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"configure/css/demo/nifty-demo.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"configure/plugins/pace/pace.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<script src=\"configure/plugins/pace/pace.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/loader.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"configure/css/loader.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"configure/css/jsapi.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  <script src=\"jQuery_4_design/AutoSearch/AutoSearchJquerySale.js\" type=\"text/javascript\"></script>\r\n");
      out.write("  <script src=\"js/jquery.validationEngine.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("  <!-- AutoSearch -->\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t/* google.load(\"visualization\", \"1\", {\r\n");
      out.write("\t\tpackages : [ \"corechart\" ]\r\n");
      out.write("\t});\r\n");
      out.write("\tgoogle.setOnLoadCallback(drawChart05);\r\n");
      out.write("\t\r\n");
      out.write("\tfunction drawChart05() {\r\n");
      out.write("\r\n");
      out.write("\t\tvar p1 = 0;\r\n");
      out.write("\t\tvar p2 = 0;\r\n");
      out.write("\t\tvar p3 = 0;\r\n");
      out.write("\t\tvar p4 = 0;\r\n");
      out.write("\t\tvar p5 = 0;\r\n");
      out.write("\t\tvar p6 = 0;\r\n");
      out.write("\t\tvar p7 = 0;\r\n");
      out.write("\t\tvar p8 = 0;\r\n");
      out.write("\t\tvar p9 = 0;\r\n");
      out.write("\t\tvar p10 = 0;\r\n");
      out.write("\t\tvar p11 = 0;\r\n");
      out.write("\t\tvar p12 = 0;\r\n");
      out.write("\t\tvar q1 = 0;\r\n");
      out.write("\t\tvar q2 = 0;\r\n");
      out.write("\t\tvar q3 = 0;\r\n");
      out.write("\t\tvar q4 = 0;\r\n");
      out.write("\t\tvar q5 = 0;\r\n");
      out.write("\t\tvar q6 = 0;\r\n");
      out.write("\t\tvar q7 = 0;\r\n");
      out.write("\t\tvar q8 = 0;\r\n");
      out.write("\t\tvar q9 = 0;\r\n");
      out.write("\t\tvar q10 = 0;\r\n");
      out.write("\t\tvar q11 = 0;\r\n");
      out.write("\t\tvar q12 = 0;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar myArray = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ];\r\n");
      out.write("\t\tvar myArray1 = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ];\r\n");
      out.write("\t\tvar myArray2 = [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]; \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* var myArray = [];\r\n");
      out.write("\t\tvar myArray1 = [];\r\n");
      out.write("\t\tvar myArray2 = []; */\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* var p = [];\r\n");
      out.write("\t\tvar q = [];\r\n");
      out.write("\t\tvar r = [];\r\n");
      out.write("\t\tvar main1 = [];\r\n");
      out.write("\t\tvar qqq1 = [ 'Vehicle No', 'Amount' ];\r\n");
      out.write("\t\tvar tot_a = \"\";\r\n");
      out.write("\t\tvar tot_b = \"\";\r\n");
      out.write("\t\tvar tot_c = \"\";\r\n");
      out.write("\t\tmain1.push(qqq1);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar a = document.getElementById(\"graph05\").value;\r\n");
      out.write("\r\n");
      out.write("\t\tvar parts = a.split(\"#\");\r\n");
      out.write("\r\n");
      out.write("\t\tj = 1;\r\n");
      out.write("\r\n");
      out.write("\t\tfor (i = 0; i < parts.length; i++) {\r\n");
      out.write("\r\n");
      out.write("\t\t\ttry {\r\n");
      out.write("\t\t\t\t/* var temp = parts[j - 1].split(\"~\"); */\r\n");
      out.write("\t\t\t\t/* var temp = parts[i].split(\"~\");\r\n");
      out.write("\t\t\t\tmyArray[i] = temp[0];\r\n");
      out.write("\t\t\t\tmyArray1[i] = temp[1];\r\n");
      out.write("\t\t\t\tmyArray2[i] = temp[2];\r\n");
      out.write("\t\t\t} catch (e) { */\r\n");
      out.write("\t\t\t\t// TODO: handle exception\r\n");
      out.write("\r\n");
      out.write("\t\t\t/*}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\talert(temp[0]+\" t0\");\r\n");
      out.write("\t\t\talert(temp[1]+\" t1\");\r\n");
      out.write("\t\t\talert(temp[2]+\" t2\"); */\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/* try {\r\n");
      out.write("\t\t\t\tvar tempx = temp[1].split(\"-\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t} catch (e) {\r\n");
      out.write("\t\t\t\t// TODO: handle exception\r\n");
      out.write("\t\t\t\ttempx[0] = 0;\r\n");
      out.write("\t\t\t\ttempx[1] = 0;\r\n");
      out.write("\t\t\t\t//myArray1[i] = parseInt(tempx[0]);\r\n");
      out.write("\t\t\t\t//myArray2[i] = parseInt(tempx[1]);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tmyArray1[i] = parseInt(tempx[0]);\r\n");
      out.write("\t\t\tmyArray2[i] = parseInt(tempx[1]); */\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//\talert(temp[0]+\">>>\"+i);\r\n");
      out.write("\t\t\t/* if (temp[0] == i) {\r\n");
      out.write("\t\t\t\tmyArray1[i] = parseInt(tempx[0]);\r\n");
      out.write("\t\t\t\tmyArray2[i] = parseInt(tempx[1]);\r\n");
      out.write("\t\t\t\t/* myArray1[i]=tempx[0];\t\r\n");
      out.write("\t\t\t\tmyArray2[i]=tempx[1];\t\r\n");
      out.write("\t\t\t\tj++;\r\n");
      out.write("\t\t\t\t */\r\n");
      out.write("\r\n");
      out.write("\t\t\t/* } else {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tmyArray1[i] = 0;\r\n");
      out.write("\t\t\t\tmyArray2[i] = 0;\r\n");
      out.write("\t\t\t}  \r\n");
      out.write("\r\n");
      out.write("\t\t\t//\t\talert(myArray[i]+\">>>\"+myArray1[i]+\">>>>\"+myArray2[i]);\r\n");
      out.write("\t\t\t//j++;\r\n");
      out.write("\t\t}*/\r\n");
      out.write("\r\n");
      out.write("\t\t/* p1 = parseInt(myArray1[1]);\r\n");
      out.write("\t\tp2 = parseInt(myArray1[2]);\r\n");
      out.write("\t\tp3 = parseInt(myArray1[3]);\r\n");
      out.write("\t\tp4 = parseInt(myArray1[4]);\r\n");
      out.write("\t\tp5 = parseInt(myArray1[5]);\r\n");
      out.write("\t\tp6 = parseInt(myArray1[6]);\r\n");
      out.write("\t\tp7 = parseInt(myArray1[7]);\r\n");
      out.write("\t\tp8 = parseInt(myArray1[8]);\r\n");
      out.write("\t\tp9 = parseInt(myArray1[9]);\r\n");
      out.write("\t\tp10 = parseInt(myArray1[10]);\r\n");
      out.write("\t\tp11 = parseInt(myArray1[11]);\r\n");
      out.write("\t\tp12 = parseInt(myArray1[12]);\r\n");
      out.write("\r\n");
      out.write("\t\tq1 = parseInt(myArray2[1]);\r\n");
      out.write("\t\tq2 = parseInt(myArray2[2]);\r\n");
      out.write("\t\tq3 = parseInt(myArray2[3]);\r\n");
      out.write("\t\tq4 = parseInt(myArray2[4]);\r\n");
      out.write("\t\tq5 = parseInt(myArray2[5]);\r\n");
      out.write("\t\tq6 = parseInt(myArray2[6]);\r\n");
      out.write("\t\tq7 = parseInt(myArray2[7]);\r\n");
      out.write("\t\tq8 = parseInt(myArray2[8]);\r\n");
      out.write("\t\tq9 = parseInt(myArray2[9]);\r\n");
      out.write("\t\tq10 = parseInt(myArray2[10]);\r\n");
      out.write("\t\tq11 = parseInt(myArray2[11]);\r\n");
      out.write("\t\tq12 = parseInt(myArray2[12]);\r\n");
      out.write("\r\n");
      out.write("\t\tvar data = google.visualization.arrayToDataTable([\r\n");
      out.write("\t\t\t\t[ 'Month', 'Total Lead', 'Closed Lead' ],\r\n");
      out.write("\t\t\t\t[ \"JAN\", p1, q1 ], [ \"FEB\", p2, q2 ],\r\n");
      out.write("\t\t\t\t[ \"MAR\", p3, q3 ], [ 'APR', p4, q4 ],\r\n");
      out.write("\t\t\t\t[ 'MAY', p5, q5 ], [ 'JUN', p6, q6 ],\r\n");
      out.write("\t\t\t\t[ 'JUL', p7, q7 ], [ 'AUG', p8, q8 ],\r\n");
      out.write("\t\t\t\t[ 'SEP', p9, q9 ], [ 'OCT', p10, q10 ],\r\n");
      out.write("\t\t\t\t[ 'NOV', p11, q11 ], [ 'DEC', p12, q12 ]\r\n");
      out.write("\r\n");
      out.write("\t\t]);\r\n");
      out.write("\r\n");
      out.write("\t\tvar options = {\r\n");
      out.write("\t\t\ttitle : 'Count Of Lead And Closed Lead',\r\n");
      out.write("\t\t\thAxis : {\r\n");
      out.write("\t\t\t\ttitle : 'Leads',\r\n");
      out.write("\t\t\t\ttitleTextStyle : {\r\n");
      out.write("\t\t\t\t\tcolor : '#333'\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tvAxis : {\r\n");
      out.write("\t\t\t\tminValue : 0\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\tvar chart = new google.visualization.ColumnChart(\r\n");
      out.write("\t\t\t\tdocument.getElementById('chart_div05'));\r\n");
      out.write("\t\tchart.draw(data, options); */\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* for (i = 0; i < parts.length; i++) {\r\n");
      out.write("\r\n");
      out.write("\t\t\tp[i] = myArray[i];\r\n");
      out.write("\r\n");
      out.write("\t\t\tq[i] = parseInt(myArray1[i]);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tr[i] = parseInt(myArray2[i]);\r\n");
      out.write("\t\t\t//alert(\"p\"+i+\":\"+p[i]);\r\n");
      out.write("\t\t\t//alert(\"q\"+i+\":\"+q[i]);\r\n");
      out.write("\r\n");
      out.write("\t\t\tucdt = [ p[i], q[i], r[i]];\r\n");
      out.write("\t\r\n");
      out.write("\t\t\talert(ucdt);\r\n");
      out.write("\r\n");
      out.write("\t\t\tmain1.push(ucdt);\r\n");
      out.write("\r\n");
      out.write("\t\t\ttot_a += p[i];\r\n");
      out.write("\t\t\ttot_b += q[i];\r\n");
      out.write("\t\t\ttot_c += r[i];\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar tot = tot_a;\r\n");
      out.write("\r\n");
      out.write("\t\tvar tot1 = tot_b;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar tot2 = tot_c;\r\n");
      out.write("\r\n");
      out.write("\t\tdocument.getElementById(\"u_c_dX\").value = main1;\r\n");
      out.write("\t\talert(main1+\" mm\");\r\n");
      out.write("\r\n");
      out.write("\t\tdocument.getElementById(\"u_c_d1X\").value = main1;\r\n");
      out.write("\t\talert('here1');\r\n");
      out.write("\t\tvar ucd2 = [ qqq1 ];\r\n");
      out.write("\t\talert('here2');\r\n");
      out.write("\t\tvar data = google.visualization.arrayToDataTable(main1);\r\n");
      out.write("\t\talert('here3');\r\n");
      out.write("\t\tvar options = {\r\n");
      out.write("\t\t\ttitle : 'Vehicle Comparison Graph',\r\n");
      out.write("\t\t\thAxis : {\r\n");
      out.write("\t\t\t\ttitle : 'Vehicle',\r\n");
      out.write("\t\t\t\ttitleTextStyle : {\r\n");
      out.write("\t\t\t\t\tcolor : '#333'\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tvAxis : {\r\n");
      out.write("\t\t\t\tminValue : 0\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\talert('here4');\r\n");
      out.write("\t\tvar chart = new google.visualization.ColumnChart(\r\n");
      out.write("\t\t\t\tdocument.getElementById('chart_div02'));\r\n");
      out.write("\t\talert('here5');\r\n");
      out.write("\t\tchart.draw(data, options);\r\n");
      out.write("\t\talert('here6'); \r\n");
      out.write("\r\n");
      out.write("\t} */\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</script> \r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t <script type=\"text/javascript\">\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("        google.charts.load('current', {'packages':['bar']});\r\n");
      out.write("\t\tgoogle.charts.setOnLoadCallback(drawStuff);\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("  \tvar myArray = [0, 0, 0,0,0,0,0,0,0,0];\r\n");
      out.write("\r\n");
      out.write("\t/*var q1=0;var q2=0;var q3=0;var q4=0;var q5=0;var q6=0;*/\r\n");
      out.write("\tvar myArray1 = [0, 0, 0,0,0,0,0,0,0,0];\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tvar p=[];\r\n");
      out.write("\tvar q=[];\r\n");
      out.write("\t\t\r\n");
      out.write("\tvar main1=[];\r\n");
      out.write("\tvar qqq1=['Root Graph ','Amount'];\r\n");
      out.write("\tvar tot_a=\"\";\r\n");
      out.write("\tvar tot_b=\"\";\r\n");
      out.write("\t \r\n");
      out.write("\tmain1.push(qqq1);\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("      function drawStuff() {\r\n");
      out.write("    \t  \r\n");
      out.write("    \t  \r\n");
      out.write("    \t  var a = document.getElementById(\"graph8\").value;\r\n");
      out.write("\t\t\t\r\n");
      out.write("    \t  \r\n");
      out.write("    \t  //alert(\"A:\"+a);\r\n");
      out.write("\t\t\t\r\n");
      out.write("    \t  var parts=a.split(\"-\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("    \t\t  \r\n");
      out.write("    \t  j=1;\t\r\n");
      out.write("    \t  \r\n");
      out.write("    \t  //alert(\"Length:\"+parts.length);\r\n");
      out.write("    \t  \r\n");
      out.write("    \t  for(i=0;i<parts.length;i++){\r\n");
      out.write("  \t\t\t\r\n");
      out.write("\t\t\t\ttry{\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar temp=parts[j-1].split(\"~\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//alert(\"TEMP:\"+temp);\r\n");
      out.write("\t\t\t\t}catch (e) {\r\n");
      out.write("\t\t\t\t\t// TODO: handle exception\r\n");
      out.write("\t\t\t\t\t temp[0]=0;\r\n");
      out.write("\t\t\t\t    temp[1]=i;\r\n");
      out.write("\t\t\t\t    \r\n");
      out.write("\t\t\t\t    \r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\tmyArray[i]=temp[0];\t\t\r\n");
      out.write("\t\t\t\tmyArray1[i]=temp[1];\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tj++;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t} \r\n");
      out.write("\t\t\t\r\n");
      out.write("    \t  for(i=0;i<parts.length;i++)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tp[i]=parseInt(myArray[i]);\t\r\n");
      out.write("\t\t\t\t//alert(\"p\"+i+\":\"+p[i]);\r\n");
      out.write("\t\t\t\tq[i]=myArray1[i];\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//alert(\"Q\"+i+\":\"+q[i]);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tucdt1 =[q[i],p[i]];\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//alert(\"UCDT::\"+ucdt);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tmain1.push(ucdt1);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\t\r\n");
      out.write("    \t    \r\n");
      out.write("\t    \r\n");
      out.write("\t\t\t/* var tot=tot_a;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar tot1=tot_b; */\r\n");
      out.write("  \t\t\t\r\n");
      out.write("\t\tdocument.getElementById(\"u_c_d3\").value = main1;\r\n");
      out.write(" \t\t\r\n");
      out.write("\t\t//alert(main);    \t \t\t \t \t\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t\tvar ucd13= [ ['Year', 'Total'], [\"abc\", 1000], [\"b\", 1000],['c', 1170],['d', 660],['e', 1030],['f', 1030],['g', 1030] ] ;\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t\t//alert(ucd1);\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t\tdocument.getElementById(\"u_c_d13\").value = main1;\r\n");
      out.write("\t\t\r\n");
      out.write(" \t\tvar ucd23= [ qqq1 ];\r\n");
      out.write(" \t\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t\tvar data= google.visualization.arrayToDataTable(main1);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar options1 = {title: 'Root Graph',};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\tvar chart = new google.charts.Bar(document.getElementById('top_x_div13'));\r\n");
      out.write("// Convert the Classic options to Material options.\r\n");
      out.write("\t\t\tchart.draw(data,google.charts.Bar.convertOptions(options1));\r\n");
      out.write("\t};\r\n");
      out.write("      \r\n");
      out.write("    </script> \r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"container\" class=\"effect mainnav-lg\">\r\n");
      out.write("\t\t<!--NAVBAR-->\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t<!--END NAVBAR-->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"boxed\">\r\n");
      out.write("\t\t\t<!--CONTENT CONTAINER-->\r\n");
      out.write("\t\t\t<div id=\"content-container\">\r\n");
      out.write("\t\t\t\t<!--Page Title-->\r\n");
      out.write("\t\t\t\t<div id=\"page-title\">\r\n");
      out.write("\t\t\t\t\t<h1 class=\"page-header text-overflow\">Root Graph </h1>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--End page title-->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!--Breadcrumb-->\r\n");
      out.write("\t\t\t\t<!-- <ol class=\"breadcrumb\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Transport</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"active\">Expense Form</li>\r\n");
      out.write("\t\t\t\t</ol> -->\r\n");
      out.write("\t\t\t\t<!--End breadcrumb-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!--Page content-->\r\n");
      out.write("\t\t\t\t<div id=\"page-content\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${graph8}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"graph8\"> \r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<script src=\"js/loader.js\" type=\"text/javascript\"></script> \r\n");
      out.write("  \t\t\t\t\t\r\n");
      out.write("  \t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"u_c_d3\" style=\"width:700px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"u_c_d13\" style=\"width:700px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t <div id=\"top_x_div13\" style=\"width: 900px; height: 350px;\"></div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--End page content-->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--END CONTENT CONTAINER-->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!--MAIN NAVIGATION-->\r\n");
      out.write("\t\t\t<nav id=\"mainnav-container\">\r\n");
      out.write("\t\t\t\t<div id=\"mainnav\">\r\n");
      out.write("\t\t\t\t\t<!--Shortcut buttons-->\r\n");
      out.write("\t\t\t\t\t<div id=\"mainnav-shortcut\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"list-unstyled\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"col-xs-4\" data-content=\"Additional Sidebar\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a id=\"demo-toggle-aside\" class=\"shortcut-grid\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-magic\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"col-xs-4\" data-content=\"Notification\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a id=\"demo-alert\" class=\"shortcut-grid\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-bullhorn\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"col-xs-4\" data-content=\"Page Alerts\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a id=\"demo-page-alert\" class=\"shortcut-grid\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-bell\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!--End shortcut buttons-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!--Menu-->\r\n");
      out.write("\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/common/leftsidebar.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t\t\t<!--End menu-->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t\t<!--END MAIN NAVIGATION-->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- FOOTER -->\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t<!-- END FOOTER -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- END OF CONTAINER -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- SETTINGS - DEMO PURPOSE ONLY -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/common/settingsForGrid.jsp", out, false);
      out.write("\r\n");
      out.write("\t<!-- END SETTINGS -->\r\n");
      out.write("\t<script src=\"configure/plugins/bootstrap-datepicker/bootstrap-datepicker.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
