/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2024-03-08 09:54:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.master;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class designation_005fmaster_005freports_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1542635938000L));
    _jspx_dependants.put("jar:file:/E:/WORKSPACE/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HSL031220/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098691290000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write(" \t<link href=\"http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&amp;subset=latin\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"configure/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"configure/css/nifty.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"configure/plugins/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"configure/plugins/switchery/switchery.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"configure/plugins/bootstrap-select/bootstrap-select.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"configure/plugins/datatables/media/css/dataTables.bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"configure/plugins/datatables/extensions/Responsive/css/dataTables.responsive.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"configure/css/demo/nifty-demo.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"configure/plugins/pace/pace.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<script src=\"configure/plugins/pace/pace.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction deleteFun(designation_id){\r\n");
      out.write("\t\t\t//alert(designation_id);\r\n");
      out.write("\t\t\tvar link = \"DeleteDesignationMaster?designation_id=\"+designation_id;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tdeleteOk = confirm('Are you sure you want to delete?');\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(deleteOk)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tlocation.href = link;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"container\" class=\"effect mainnav-lg\">\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/common/data-tableheader.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t<div class=\"boxed\">\r\n");
      out.write("\t\t\t<div id=\"content-container\">\r\n");
      out.write("\t\t\t\t<div id=\"page-title\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"page-content\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel\">\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<a href=\"DesignationMaster\"><button style=\"margin-left: 20px; height: 30px; width: 100px;\">Add New</button></a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"panel-title\">Designation Master Report</h3>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t\t<table id=\"demo-dt-basic\" class=\"table table-striped table-bordered\" cellspacing=\"0\" width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Sr.No</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Designation Name</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Remark</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Action</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Action</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t ");
int i=1; 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t ");
      //  c:forEach
      org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /master/designation_master_reports.jsp(66,9) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${designationMasterDetails}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /master/designation_master_reports.jsp(66,9) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("designationMasterDetails");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>");
            out.print(i++ );
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>");
            if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return;
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>");
            if (_jspx_meth_c_005fout_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return;
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\"><a style=\"text-decoration: none;color: green;\" title=\"Update\" href=\"UpdatedesignationMaster?designation_id=");
            if (_jspx_meth_c_005fout_005f2(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return;
            out.write("\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<img alt=\"Update\" src=\"configure/img/pencil.png\"></a>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t   </td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t");
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t   \r\n");
            out.write("\t\t\t\t\t\t\t\t\t   <td align=\"center\"><a style=\"text-decoration: none;color: red;\" title=\"Delete\" >\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<img alt=\"\" height=\"20px;\" src=\"configure/img/recycle-bin.svg\" onclick=\"deleteFun(");
            if (_jspx_meth_c_005fout_005f3(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return;
            out.write(");\"></a>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t   </td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t   \r\n");
            out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
        _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      }
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/common/leftsidebar.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- FOOTER -->\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t<!-- END FOOTER -->\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"demo-set\" class=\"demo-set\">\r\n");
      out.write("\t\t<div class=\"demo-set-body bg-dark\">\r\n");
      out.write("\t\t\t<div id=\"demo-set-alert\"></div>\r\n");
      out.write("\t\t\t<div class=\"demo-set-content clearfix\">\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-6 col-md-4\">\r\n");
      out.write("\t\t\t\t\t<h4 class=\"text-lg mar-btm\">Animations</h4>\r\n");
      out.write("\t\t\t\t\t<div id=\"demo-anim\" class=\"mar-btm\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"form-checkbox form-icon active\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"checkbox\" checked=\"\"> Enable Animations\r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<p>Transition effects</p>\r\n");
      out.write("\t\t\t\t\t<select id=\"demo-ease\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"effect\" selected>ease (Default)</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"easeInQuart\">easeInQuart</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"easeOutQuart\">easeOutQuart</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"easeInBack\">easeInBack</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"easeOutBack\">easeOutBack</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"easeInOutBack\">easeInOutBack</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"steps\">Steps</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"jumping\">Jumping</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"rubber\">Rubber</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t<hr class=\"bord-no\">\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<h4 class=\"text-lg mar-btm\">Navigation</h4>\r\n");
      out.write("\t\t\t\t\t<div class=\"mar-btm\">\r\n");
      out.write("\t\t\t\t\t\t<label id=\"demo-nav-fixed\" class=\"form-checkbox form-icon\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"checkbox\"> Fixed\r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<label id=\"demo-nav-coll\" class=\"form-checkbox form-icon\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\"> Collapsed\r\n");
      out.write("\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t<hr class=\"bord-no\">\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<h4 class=\"text-lg mar-btm\">Off Canvas Navigation</h4>\r\n");
      out.write("\t\t\t\t\t<select id=\"demo-nav-offcanvas\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"none\" selected disabled=\"disabled\">-- Select Mode --</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"push\">Push</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"slide\">Slide in on top</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"reveal\">Reveal</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-6 col-md-3\">\r\n");
      out.write("\t\t\t\t\t<h4 class=\"text-lg mar-btm\">Aside</h4>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-block\">\r\n");
      out.write("\t\t\t\t\t\t<label id=\"demo-asd-vis\" class=\"form-checkbox form-icon\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"checkbox\"> Visible\r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t<label id=\"demo-asd-fixed\" class=\"form-checkbox form-icon\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"checkbox\"> Fixed\r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t<label id=\"demo-asd-align\" class=\"form-checkbox form-icon\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"checkbox\"> Aside on the left side\r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t<label id=\"demo-asd-themes\" class=\"form-checkbox form-icon\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"checkbox\"> Bright Theme\r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<hr class=\"bord-no\">\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<h4 class=\"text-lg mar-btm\">Header / Navbar</h4>\r\n");
      out.write("\t\t\t\t\t<label id=\"demo-navbar-fixed\" class=\"form-checkbox form-icon\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\"> Fixed\r\n");
      out.write("\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t<hr class=\"bord-no\">\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<h4 class=\"text-lg mar-btm\">Footer</h4>\r\n");
      out.write("\t\t\t\t\t<label id=\"demo-footer-fixed\" class=\"form-checkbox form-icon\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\"> Fixed\r\n");
      out.write("\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-12 col-md-5\">\r\n");
      out.write("\t\t\t\t\t<div id=\"demo-theme\">\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"text-lg mar-btm\">Color Themes</h4>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"demo-theme-btn\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"demo-theme demo-a-light add-tooltip\" data-theme=\"theme-light\" data-type=\"a\" data-title=\"(A). Light\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-brand\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-head\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-nav\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"demo-theme demo-a-navy add-tooltip\" data-theme=\"theme-navy\" data-type=\"a\" data-title=\"(A). Navy Blue\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-brand\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-head\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-nav\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"demo-theme demo-a-ocean add-tooltip\" data-theme=\"theme-ocean\" data-type=\"a\" data-title=\"(A). Ocean\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-brand\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-head\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-nav\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"demo-theme demo-a-lime add-tooltip\" data-theme=\"theme-lime\" data-type=\"a\" data-title=\"(A). Lime\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-brand\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-head\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-nav\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"demo-theme demo-a-purple add-tooltip\" data-theme=\"theme-purple\" data-type=\"a\" data-title=\"(A). Purple\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-brand\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-head\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-nav\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"demo-theme demo-a-dust add-tooltip\" data-theme=\"theme-dust\" data-type=\"a\" data-title=\"(A). Dust\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-brand\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-head\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-nav\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"demo-theme demo-a-mint add-tooltip\" data-theme=\"theme-mint\" data-type=\"a\" data-title=\"(A). Mint\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-brand\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-head\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-nav\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"demo-theme demo-a-yellow add-tooltip\" data-theme=\"theme-yellow\" data-type=\"a\" data-title=\"(A). Yellow\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-brand\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-head\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-nav\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"demo-theme demo-a-well-red add-tooltip\" data-theme=\"theme-well-red\" data-type=\"a\" data-title=\"(A). Well Red\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-brand\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-head\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-nav\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"demo-theme demo-a-coffee add-tooltip\" data-theme=\"theme-coffee\" data-type=\"a\" data-title=\"(A). Coffee\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-brand\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-head\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-nav\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"demo-theme demo-a-prickly-pear add-tooltip\" data-theme=\"theme-prickly-pear\" data-type=\"a\" data-title=\"(A). Prickly pear\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-brand\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-head\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-nav\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"demo-theme demo-a-dark add-tooltip\" data-theme=\"theme-dark\" data-type=\"a\" data-title=\"(A). Dark\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-brand\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-head\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-nav\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"demo-theme-btn\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"demo-theme demo-b-light add-tooltip\" data-theme=\"theme-light\" data-type=\"b\" data-title=\"(B). Light\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-brand\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-head\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-nav\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"demo-theme demo-b-navy add-tooltip\" data-theme=\"theme-navy\" data-type=\"b\" data-title=\"(B). Navy Blue\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-brand\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-head\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-nav\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"demo-theme demo-b-ocean add-tooltip\" data-theme=\"theme-ocean\" data-type=\"b\" data-title=\"(B). Ocean\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-brand\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-head\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-nav\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"demo-theme demo-b-lime add-tooltip\" data-theme=\"theme-lime\" data-type=\"b\" data-title=\"(B). Lime\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-brand\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-head\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-nav\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"demo-theme demo-b-purple add-tooltip\" data-theme=\"theme-purple\" data-type=\"b\" data-title=\"(B). Purple\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-brand\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-head\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-nav\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"demo-theme demo-b-dust add-tooltip\" data-theme=\"theme-dust\" data-type=\"b\" data-title=\"(B). Dust\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-brand\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-head\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-nav\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"demo-theme demo-b-mint add-tooltip\" data-theme=\"theme-mint\" data-type=\"b\" data-title=\"(B). Mint\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-brand\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-head\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-nav\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"demo-theme demo-b-yellow add-tooltip\" data-theme=\"theme-yellow\" data-type=\"b\" data-title=\"(B). Yellow\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-brand\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-head\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-nav\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"demo-theme demo-b-well-red add-tooltip\" data-theme=\"theme-well-red\" data-type=\"b\" data-title=\"(B). Well red\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-brand\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-head\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-nav\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"demo-theme demo-b-coffee add-tooltip\" data-theme=\"theme-coffee\" data-type=\"b\" data-title=\"(B). Coofee\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-brand\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-head\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-nav\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"demo-theme demo-b-prickly-pear add-tooltip\" data-theme=\"theme-prickly-pear\" data-type=\"b\" data-title=\"(B). Prickly pear\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-brand\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-head\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-nav\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"demo-theme demo-b-dark add-tooltip\" data-theme=\"theme-dark\" data-type=\"b\" data-title=\"(B). Dark\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-brand\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-head\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-nav\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"demo-theme-btn\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"demo-theme demo-c-light add-tooltip\" data-theme=\"theme-light\" data-type=\"c\" data-title=\"(C). Light\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-brand\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-head\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-nav\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"demo-theme demo-c-navy add-tooltip\" data-theme=\"theme-navy\" data-type=\"c\" data-title=\"(C). Navy Blue\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-brand\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-head\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-nav\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"demo-theme demo-c-ocean add-tooltip\" data-theme=\"theme-ocean\" data-type=\"c\" data-title=\"(C). Ocean\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-brand\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-head\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-nav\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"demo-theme demo-c-lime add-tooltip\" data-theme=\"theme-lime\" data-type=\"c\" data-title=\"(C). Lime\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-brand\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-head\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-nav\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"demo-theme demo-c-purple add-tooltip\" data-theme=\"theme-purple\" data-type=\"c\" data-title=\"(C). Purple\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-brand\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-head\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-nav\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"demo-theme demo-c-dust add-tooltip\" data-theme=\"theme-dust\" data-type=\"c\" data-title=\"(C). Dust\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-brand\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-head\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-nav\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"demo-theme demo-c-mint add-tooltip\" data-theme=\"theme-mint\" data-type=\"c\" data-title=\"(C). Mint\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-brand\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-head\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-nav\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"demo-theme demo-c-yellow add-tooltip\" data-theme=\"theme-yellow\" data-type=\"c\" data-title=\"(C). Yellow\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-brand\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-head\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-nav\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"demo-theme demo-c-well-red add-tooltip\" data-theme=\"theme-well-red\" data-type=\"c\" data-title=\"(C). Well Red\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-brand\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-head\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-nav\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"demo-theme demo-c-coffee add-tooltip\" data-theme=\"theme-coffee\" data-type=\"c\" data-title=\"(C). Coffee\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-brand\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-head\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-nav\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"demo-theme demo-c-prickly-pear add-tooltip\" data-theme=\"theme-prickly-pear\" data-type=\"c\" data-title=\"(C). Prickly pear\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-brand\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-head\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-nav\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"demo-theme demo-c-dark add-tooltip\" data-theme=\"theme-dark\" data-type=\"c\" data-title=\"(C). Dark\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-brand\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-head\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"demo-theme-nav\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"pad-all text-left\">\r\n");
      out.write("\t\t\t\t<hr class=\"hr-sm\">\r\n");
      out.write("\t\t\t\t<p class=\"demo-set-save-text\">* All settings will be saved automatically.</p>\r\n");
      out.write("\t\t\t\t<button id=\"demo-reset-settings\" class=\"btn btn-primary btn-labeled fa fa-refresh mar-btm\">Restore Default Settings</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<button id=\"demo-set-btn\" class=\"btn btn-sm\"><i class=\"fa fa-cog fa-2x\"></i></button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"configure/js/jquery-2.1.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"configure/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"configure/plugins/fast-click/fastclick.min.js\"></script>\r\n");
      out.write("\t<script src=\"configure/js/nifty.min.js\"></script>\r\n");
      out.write("\t<script src=\"configure/plugins/switchery/switchery.min.js\"></script>\r\n");
      out.write("\t<script src=\"configure/plugins/bootstrap-select/bootstrap-select.min.js\"></script>\r\n");
      out.write("\t<script src=\"configure/plugins/datatables/media/js/jquery.dataTables.js\"></script>\r\n");
      out.write("\t<script src=\"configure/plugins/datatables/media/js/dataTables.bootstrap.js\"></script>\r\n");
      out.write("\t<script src=\"configure/plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js\"></script>\r\n");
      out.write("\t<script src=\"configure/js/demo/nifty-demo.min.js\"></script>\r\n");
      out.write("\t<script src=\"configure/js/demo/tables-datatables.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /master/designation_master_reports.jsp(69,14) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${designationMasterDetails.designation_name}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
    if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /master/designation_master_reports.jsp(70,14) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${designationMasterDetails.remark}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
    if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /master/designation_master_reports.jsp(71,136) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${designationMasterDetails.designation_id}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f2 = _jspx_th_c_005fout_005f2.doStartTag();
    if (_jspx_th_c_005fout_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f3 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /master/designation_master_reports.jsp(79,93) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${designationMasterDetails.designation_id}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f3 = _jspx_th_c_005fout_005f3.doStartTag();
    if (_jspx_th_c_005fout_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f3);
    return false;
  }
}
